Repository mattermost/mattermost-cloud, pull requests merged in 2020-11, with the labels that each got.

#349 Releasing operator v1.10.0
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/crds/mm_mattermostrestoredb_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role_binding.yaml
Labels: 2: Infra Review, kind/feature, release-note

#348 MM-30167 Remove unnecessary error-prone DNS check
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, release-note

#345 MM-29860 - Add flag to require annotated installations
  cmd/cloud/server.go
  model/installation_request.go
  model/installation_request_test.go
Labels: release-note

#352 Force AmazonS3SSL to false for bifrost
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#353 Add filestore test suite to ctest tool
  cmd/tools/ctest/ctest.go
  cmd/tools/ctest/database.go
  cmd/tools/ctest/filestore.go
  cmd/tools/ctest/logger.go
  cmd/tools/ctest/main.go
  cmd/tools/ctest/test.go
  cmd/tools/ctest/webhooks.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#355 Add bifrost network policy and better k8s probes
  go.mod
  go.sum
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/s3.go
  manifests/bifrost/bifrost.yaml
Labels: 2: Infra Review, kind/feature, release-note

#356 Use affinity/toleration for services apps in the cluster
  cmd/cloud/cluster.go
  helm-charts/prometheus_operator_values.yaml
  helm-charts/prometheus_values.yaml
  helm-charts/teleport_values.yaml
  helm-charts/thanos_values.yaml
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/prometheus.go
  internal/provisioner/utility_group.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#357 collect only the original node metadata information
  internal/tools/kops/instance_groups.go
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#358 [MM 30012] Improvements to Thanos and Prometheus Operator utility groups.
  helm-charts/prometheus_operator_values.yaml
  helm-charts/thanos_values.yaml
Labels: release-note

#359 add mattermost job check to allow to talk with bifrost
  manifests/bifrost/bifrost.yaml
Labels: kind/bug, release-note

#354 MM-19774 - Support configuration of single-tenant RDS via Provisioner API
  cmd/cloud/installation.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/mocks/model/installation_database.go
  internal/store/installation.go
  internal/store/installation_dto_test.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/database.go
  internal/tools/aws/database_test.go
  internal/tools/aws/helpers.go
  internal/tools/aws/rds.go
  internal/tools/aws/rds_test.go
  model/installation.go
  model/installation_database.go
  model/installation_database_test.go
  model/installation_request.go
  model/installation_request_test.go
  model/single_tenant_database.go
  model/single_tenant_database_test.go
Labels: release-note

#361 ctest upgrades and refactor
  cmd/tools/ctest/database.go
  cmd/tools/ctest/filestore.go
  cmd/tools/ctest/logger.go
  cmd/tools/ctest/test.go
  cmd/tools/ctest/webhooks.go
Labels: 2: Dev Review, release-note

#360 Add balanced cluster scheduling for installations
  cmd/cloud/server.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#363 Change required Helm client version to 3.4.x
  README.md
Labels: release-note-none

#362 MM29235 - Cleanup Helm migration code
  Makefile
  README.md
  build/Dockerfile
  cmd/cloud/server.go
  internal/provisioner/fluentbit.go
  internal/provisioner/helm2_utils.go
  internal/provisioner/helm_migrate.go
  internal/provisioner/helm_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  internal/tools/helm/cmd.go
Labels: release-note

#366 [MM-30513] Adapt NGINX autoscaling to meet new cluster sizes.
  helm-charts/nginx_values.yaml
Labels: kind/cleanup, release-note

#369 [MM-30618] Release Mattermost Operator v1.11.0.
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#368 Reduce prometheus data retention to 5 days and increase volume size.
  helm-charts/prometheus_operator_values.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#367 MM-30529 Add ability to specify filestore, db type, and Installation size to load testing tool
  cmd/tools/cloudburst/cloudburst.go
Labels: 4: Reviews Complete, release-note

#374 [MM-30522] Enable DNS metrics scrape on Prometheus
  helm-charts/prometheus_operator_values.yaml
Labels: 2: Infra Review, release-note

#373 Add DNS filter to cloud installation list cmd
  cmd/cloud/installation.go
Labels: 2: Dev Review, release-note

#370 groups: add groups status endpoint
  cmd/cloud/group.go
  internal/api/group.go
  internal/api/group_test.go
  model/client.go
  model/group_status.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#378 Rename InstallationsUnstable to InstallationsUpdating in group status
  internal/api/group_test.go
  internal/store/group.go
  internal/store/group_test.go
  model/group_status.go
  model/group_status_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#380 [MM-30945] Increase number of max installations per database to 200.
  internal/tools/aws/constants.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note
