Repository mattermost/mattermost-cloud, pull requests merged in 2020-05, with the labels that each got.

#210 Fix ineffectual debug log setting when in dev mode
  cmd/cloud/server.go
Labels: 3: Reviews Complete, release-note

#211 fix missing parameters and default values
  internal/api/request_test.go
  model/cluster_request.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#214 Remove cert manager and use AWS ACM in public ngix
  build/Dockerfile
  certmanager-manifests/cluster-issuer.yaml
  certmanager-manifests/crds.yaml
  cmd/cloud/cluster.go
  helm-charts/cert-manager_values.yaml
  helm-charts/public-nginx_values.yaml
  internal/api/request_test.go
  internal/provisioner/certmanager.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_utils.go
  internal/provisioner/public_nginx.go
  internal/provisioner/utility_group.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/k8s/client.go
  internal/tools/k8s/client_test.go
  internal/tools/k8s/clusterissuer.go
  internal/tools/k8s/clusterissuer_test.go
  internal/tools/k8s/manifest.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Infra Review, kind/feature, priority/critical-urgent, release-note

#213 Add cluster resize functionality
  cmd/cloud/cluster.go
  go.mod
  go.sum
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_utils.go
  internal/provisioner/kops_utils_test.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/cluster_test.go
  internal/supervisor/group_test.go
  internal/supervisor/installation_test.go
  internal/tools/kops/cluster.go
  internal/tools/kops/cmd.go
  model/client.go
  model/cluster_states.go
  model/installation_test.go
Labels: 4: Reviews Complete, release-note

#212 update documentation readme
  README.md
Labels: kind/documentation, release-note-none

#209 MM-23151: Added a new database abstraction to support multitenant RDS clusters
  cmd/cloud/installation.go
  cmd/cloud/server.go
  go.mod
  go.sum
  internal/mocks/aws-tools/client.go
  internal/mocks/model/installation_database.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/migrations.go
  internal/store/multitenant_database.go
  internal/store/multitenant_database_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client_test.go
  internal/tools/aws/constants.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/database_test.go
  internal/tools/aws/helpers.go
  internal/tools/aws/rds_test.go
  internal/tools/aws/secrets_manager.go
  internal/tools/utils/utils.go
  model/general.go
  model/installation_database.go
  model/installation_database_test.go
  model/multitenant_database.go
  model/multitenant_database_test.go
Labels: release-note

#215 MM-23151: changed multi-tenant database's locking pattern
  cmd/cloud/server.go
  internal/store/multitenant_database.go
  internal/tools/aws/client_test.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/utils/utils.go
Labels: 4: Reviews Complete, release-note

#216 Add installation scaling
  cmd/cloud/installation.go
  internal/api/installation_test.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, release-note

#217 Add job and make to check the outdated modules
  .circleci/config.yml
  Makefile
  go.mod
  go.sum
Labels: 2: Dev Review, 2: Infra Review, release-note

#218 dependencies: update several dependencies
  go.mod
  go.sum
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/iam.go
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/resource_tagging.go
  internal/mocks/aws-sdk/route53.go
  internal/mocks/aws-sdk/s3.go
  internal/mocks/aws-sdk/secrets_manager.go
Labels: 4: Reviews Complete, kind/cleanup, priority/important-soon, release-note

#219 Add option to change cluster AMI on upgrade
  cmd/cloud/cluster.go
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_utils.go
  internal/provisioner/kops_utils_test.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/client.go
  model/cluster_request.go
  model/cluster_request_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#223 MM-25556: multi tenant RDS databases should be provisioned to the correct VPC in a multi cluster environment
  internal/store/migrations.go
  internal/store/multitenant_database.go
  internal/store/multitenant_database_test.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_test.go
  model/multitenant_database.go
Labels: 4: Reviews Complete, release-note

#224 Stale installation supervisor fix
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/iam.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#222 Add installation and group env var patching logic
  cmd/cloud/group.go
  cmd/cloud/installation.go
  cmd/cloud/utils.go
  internal/api/group_test.go
  model/env.go
  model/env_test.go
  model/group_request.go
  model/group_request_test.go
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, release-note

#225 Stale cluster and cluster installation supervisor fix
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/cluster_test.go
Labels: 4: Reviews Complete, release-note
