Repository mattermost/mattermost-cloud, pull requests merged in 2020-12, with the labels that each got.

#381 Minor typo fix
  README.md
Labels: release-note-none

#379 Installation group improvements
  internal/api/context.go
  internal/api/group.go
  internal/store/group.go
  internal/store/group_test.go
  internal/supervisor/group.go
  internal/supervisor/installation_test.go
  model/group_request.go
  model/group_request_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#365 MM-30277 Add metrics to measure elapsed Installation creation time
  cmd/cloud/server.go
  file
  go.mod
  go.sum
  internal/api/api.go
  internal/metrics/metrics.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: release-note

#375 MM-28937 Add ability to change version of Utility (Helm) values files without rebuild
  cmd/cloud/cluster.go
  cmd/tools/cloudburst/cloudburst.go
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/fluentbit.go
  internal/provisioner/fluentbit_test.go
  internal/provisioner/helm_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  internal/tools/aws/client_test.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#382 Update Mattermost operator to v1.11.1
  go.mod
  go.sum
  helm-charts/prometheus_operator_values.yaml
  helm-charts/thanos_values.yaml
  internal/api/request_test.go
  internal/provisioner/kops_utils.go
  internal/provisioner/thanos.go
  manifests/operator-manifests/mattermost/operator.yaml
  model/cluster_utility.go
Labels: kind/feature, release-note

#337 remove ssh access from 0.0.0.0/0
  cmd/cloud/server.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/vpc.go
  internal/tools/kops/cluster.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, priority/important-soon, release-note

#384 Fix CnC vpc name from <env-command-control to mattermost-cloud-<env>-command-control
  internal/provisioner/kops_provisioner_cluster.go
Labels: kind/bug, release-note

#383 MM-31043 Allow utility values to be fetched from authenticated sources
  cmd/cloud/server.go
  internal/provisioner/helm_utils.go
  internal/tools/exechelper/run.go
  internal/tools/helm/run.go
  model/cluster_utility.go
Labels: 2: Dev Review, release-note

#387 MM-30591 Bump minor version of Helm to 3.4.1 from 3.3.4
  Makefile
Labels: 2: Dev Review, 2: Infra Review, release-note

#372 [MM-30582] Add prometheus-adapter to implement custom metrics APIService
  internal/provisioner/kops_provisioner_cluster.go
  manifests/prometheus-adapter/prometheus-adapter.yaml
Labels: 2: Dev Review, 2: Infra Review, release-note

#364 MM-30448 - Add DB Connection check URL to Secret when using Postgres database
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
Labels: 4: Reviews Complete, release-note

#388 [MM-31330] Reduce retention period for Prometheus local data.
  helm-charts/prometheus_operator_values.yaml
Labels: kind/cleanup, release-note

#389 Add kops client caching
  cmd/cloud/server.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_test.go
  internal/provisioner/kops_utils.go
  internal/tools/kops/cmd.go
Labels: 4: Reviews Complete, kind/feature, release-note

#386 webhooks: add environment to the webhooks payload
  cmd/cloud/server.go
  internal/api/cluster.go
  internal/api/context.go
  internal/api/installation.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/installation.go
Labels: kind/documentation, kind/feature, release-note

#385 Minor documentation fix
  README.md
Labels: release-note-none
