Repository mattermost/mattermost-cloud, pull requests merged in 2020-07, with the labels that each got.

#259 Add cluster scale up logic
  cmd/cloud/server.go
  go.mod
  go.sum
  internal/provisioner/fluentbit_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/k8s/manifest_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#261 Check ID field in webhook listener
  cmd/tools/cwl/cwl.go
Labels: 2: Dev Review, release-note-none

#262 MM-26670 Add ability to look up an Installation by DNS name
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  model/client.go
  model/installation.go
  model/installation_request.go
Labels: 2: Infra Review, release-note

#266 [MM-27201] Move k8s client out of the internal folder for inclusion elsewhere
  internal/api/common_test.go
  internal/api/context.go
  internal/provisioner/helm_utils.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_utils.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  k8s/README.md
  k8s/apiservice.go
  k8s/apiservice_test.go
  k8s/bindings.go
  k8s/bindings_test.go
  k8s/client.go
  k8s/client_test.go
  k8s/configmaps.go
  k8s/configmaps_test.go
  k8s/custom_resources.go
  k8s/custom_resources_test.go
  k8s/daemonset.go
  k8s/daemonset_test.go
  k8s/deployments.go
  k8s/deployments_test.go
  k8s/helpers.go
  k8s/helpers_test.go
  k8s/manifest.go
  k8s/manifest_test.go
  k8s/namespaces.go
  k8s/namespaces_test.go
  k8s/networkpolicy.go
  k8s/networkpolicy_test.go
  k8s/poddisruptionbudget.go
  k8s/poddisruptionbudget_test.go
  k8s/resources.go
  k8s/roles.go
  k8s/roles_test.go
  k8s/secrets.go
  k8s/secrets_test.go
  k8s/service_accounts.go
  k8s/service_accounts_test.go
  k8s/services.go
  k8s/services_test.go
  k8s/statefulset.go
  k8s/statefulset_test.go
  k8s/storage_class.go
  k8s/storage_class_test.go
Labels: kind/cleanup, release-note

#267 Add Postgres single-tenant database option
  cmd/cloud/installation.go
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/iam.go
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/resource_tagging.go
  internal/mocks/aws-sdk/route53.go
  internal/mocks/aws-sdk/s3.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/mocks/logger/logrus.go
  internal/tools/aws/client_test.go
  internal/tools/aws/database.go
  internal/tools/aws/database_test.go
  internal/tools/aws/rds.go
  internal/tools/aws/rds_test.go
  internal/tools/utils/utils.go
  model/installation_database.go
  model/installation_database_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#263 [MΜ 26623] Migrate to single NGINX deployment, enable autoscaling.
  README.md
  cmd/cloud/cluster.go
  helm-charts/nginx_values.yaml
  helm-charts/private-nginx_values.yaml
  helm-charts/prometheus_values.yaml
  internal/api/request_test.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/public_nginx.go
  internal/provisioner/utility_group.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/constants.go
  k8s/manifest_test.go
  kubernetes/ingress.yaml
  manifests/network-policies/mm-installation-netpol.yaml
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, kind/feature, release-note

#268 Adding support for PersistentVolume and PersistentVolumeClaim in k8s …
  k8s/manifest.go
  k8s/persistentvolume.go
  k8s/persistentvolume_test.go
Labels: 2: Infra Review, kind/feature, release-note

#272 Use PostgreSQL version 11.7 for new databases
  internal/tools/aws/constants.go
  internal/tools/aws/rds.go
Labels: 4: Reviews Complete, kind/feature, release-note

#270 MM-27216 - added MM_CLOUD_INSTALLATION_ID
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: release-note

#269 Use the AWS_REGION set in the config and not hardcoded ones
  .circleci/config.yml
  .gitignore
  Makefile
  cmd/cloud/server.go
  hack/boilerplate/boilerplate.generatego.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/iam.go
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/resource_tagging.go
  internal/mocks/aws-sdk/route53.go
  internal/mocks/aws-sdk/s3.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/mocks/aws-tools/client.go
  internal/mocks/aws-tools/doc.go
  internal/mocks/logger/doc.go
  internal/mocks/logger/logrus.go
  internal/mocks/model/doc.go
  internal/mocks/model/installation_database.go
  internal/tools/aws/client_test.go
  internal/tools/aws/database_test.go
  internal/tools/aws/general.go
  internal/tools/aws/rds.go
  internal/tools/aws/rds_test.go
  internal/tools/terraform/plan.go
  scripts/go_install.sh
  scripts/push-docker-pr.sh
  scripts/push-docker.sh
  scripts/verify-boilerplate.sh
Labels: 4: Reviews Complete, kind/bug, kind/feature, release-note

#265 Update kops and golang
  .circleci/config.yml
  Makefile
Labels: 4: Reviews Complete, kind/cleanup, release-note

#271 Add database endpoint init check to single tenant databases
  internal/tools/aws/database.go
  k8s/custom_resources.go
  k8s/custom_resources_test.go
  k8s/manifest.go
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#274 NewFromConfig KubeClient creation option, rename and refactor 'New' to 'NewFromFile'
  internal/provisioner/helm_utils.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_utils.go
  k8s/client.go
Labels: 4: Reviews Complete, kind/feature, release-note

#275 rds: fix azs to get at least 2 az
  internal/tools/aws/rds.go
Labels: 4: Reviews Complete, kind/bug, release-note-none

#276 mm-operator: update operator to 1.6.1 due infinite reconcile loop
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 2: Infra Review, kind/bug, release-note

#277 Change the helm install link
  README.md
Labels: 4: Reviews Complete, release-note-none

#273 [MM-27278] Adding ability to attach custom IAM Policy to Kops node IAM Instance Profiles
  Makefile
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/sts.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation_test.go
  internal/testlib/aws.go
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/constants.go
  internal/tools/aws/iam.go
  internal/tools/aws/sts.go
Labels: 2: Dev Review, kind/feature, release-note
