Repository mattermost/mattermost-cloud, pull requests merged in 2020-02, with the labels that each got.

#148 Prevent group deletion with installation members
  internal/api/cluster.go
  internal/api/group.go
  internal/api/group_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  model/installation.go
Labels: 3: Reviews Complete

#143 MM-20995 Allow cluster utility versions to be managed via the API
  .gitignore
  cmd/cloud/cluster.go
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/provisioner/fluentbit.go
  internal/provisioner/helm_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/utility_group.go
  internal/store/cluster.go
  internal/store/cluster_test.go
  internal/store/migrations.go
  internal/supervisor/cluster.go
  model/client.go
  model/cluster.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 3: Reviews Complete

#150 update mm crds
  operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  operator-manifests/mattermost/crds/mm_mattermostrestoredb_crd.yaml
Labels: 2: Dev Review

#155 Add Helm log wrapper
  internal/provisioner/helm_utils.go
  internal/tools/helm/cmd.go
  internal/tools/helm/commands.go
  internal/tools/helm/run.go
Labels: 3: Reviews Complete

#152 MM-22354 Pin known working versions of the cluster utilities by default
  cmd/cloud/cluster.go
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/fluentbit.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/utility_group.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Infra Review

#149 MM-22054 Create new storageclass with volumeBindingMode: WaitForFirstConsumer option
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/k8s/storage_class.go
  internal/tools/k8s/storage_class_test.go
Labels: 2: Dev Review

#154 MM-22353 Add a migration to insert default values for UtilityMetadata
  internal/store/migrations.go
Labels: 3: Reviews Complete

#157 MM-22391 Run helm init during provision
  internal/provisioner/helm_utils.go
  internal/provisioner/utility_group.go
Labels: 3: Reviews Complete

#158 Set default RDS instance to db.t3.small
  internal/tools/aws/rds.go
Labels: 2: Dev Review, 2: Infra Review

#156 MM-15369 Add API endpoint to allow changing version of Installation Groups
  internal/api/group.go
  internal/api/group_test.go
Labels: 2: Infra Review

#161 Add Mattermost Env for Installations
  cmd/cloud/installation.go
  go.mod
  go.sum
  internal/api/cluster.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/k8s/client.go
  model/client.go
  model/env.go
  model/env_test.go
  model/installation.go
  model/installation_request.go
  model/installation_request_test.go
  model/installation_states.go
  model/installation_test.go
Labels: 3: Reviews Complete

#163 fix error when existing installation does not have the mm env
  internal/store/installation.go
  model/env.go
Labels: 3: Reviews Complete
