Repository mattermost/mattermost-cloud, pull requests merged in 2020-04, with the labels that each got.

#179 Enable group functionality
  cmd/cloud/group.go
  cmd/cloud/installation.go
  internal/api/context.go
  internal/api/group.go
  internal/api/helpers.go
  internal/api/installation.go
  internal/store/group.go
  internal/store/group_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/group.go
  internal/supervisor/group_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/group_request.go
  model/installation.go
  model/installation_request.go
  model/installation_test.go
Labels: 3: Reviews Complete

#184 update kubectl to match the kops image and bump alpine
  Makefile
Labels: 3: Reviews Complete

#185 go: update go to use 1.14.1
  .circleci/config.yml
  Makefile
  build/Dockerfile
  go.mod
Labels: 3: Reviews Complete

#181 MM-23550 Add DELETE permission for S3 buckets for cloud user
  internal/tools/aws/iam.go
Labels: 2: Infra Review

#183 operators: bump minio and mattermost operators
  operator-manifests/mattermost/operator.yaml
  operator-manifests/minio/minio-operator.yaml
Labels: 3: Reviews Complete

#186 Improve group leave logic
  cmd/cloud/group.go
  file
  internal/api/group_test.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  model/client.go
  model/group_request.go
Labels: 3: Reviews Complete

#191 dockerfile: add cert-manager manifests to the image
  build/Dockerfile
Labels: 3: Reviews Complete

#188 Allow for empty image and/or version group values
  cmd/cloud/group.go
  cmd/cloud/installation.go
  internal/api/group.go
  internal/api/group_test.go
  model/group_request.go
  model/installation.go
Labels: 3: Reviews Complete

#192 Fixing bug during adding new repos
  internal/provisioner/helm_utils.go
  internal/provisioner/utility_group.go
Labels: 3: Reviews Complete

#193 Refactor installation update logic
  cmd/cloud/flags.go
  cmd/cloud/group.go
  cmd/cloud/installation.go
  internal/api/group.go
  internal/api/group_test.go
  internal/api/installation.go
  internal/api/installation_test.go
  model/client.go
  model/group_request.go
  model/installation_request.go
  model/installation_request_test.go
Labels: 2: Infra Review

#182 MM-22708: added support to encrypt RDS database at rest
  Makefile
  internal/mocks/aws-sdk/kms.go
  internal/testlib/aws.go
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/constants.go
  internal/tools/aws/database.go
  internal/tools/aws/database_test.go
  internal/tools/aws/helpers.go
  internal/tools/aws/kms.go
  internal/tools/aws/rds.go
  internal/tools/aws/rds_test.go
Labels: 3: Reviews Complete

#190 Scan image for security vulnerabilities
  .circleci/config.yml
Labels: 3: Reviews Complete

#178 Mm 22392 - Adding support for NGINX for new installations
  go.mod
  go.sum
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_utils.go
  internal/provisioner/utility_group.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/k8s/client.go
Labels: 2: Infra Review

#197 Disable RDS encryption logic
  internal/tools/aws/database.go
  internal/tools/aws/database_test.go
  internal/tools/aws/rds.go
Labels: 2: Dev Review

#201 pr/template: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, release-note-none

#203 Always log to DEBUG level from AWS session
  internal/tools/aws/session.go
Labels: release-note-none

#194 MM-23742 Moving DNS registration step before installation creation and adding check for certificate approve status
  internal/provisioner/kops_utils.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/installation_states.go
Labels: 2: Infra Review, kind/feature, release-note

#195 Check if group is deleted before joining installations
  internal/api/installation.go
  internal/api/installation_test.go
  model/cluster_installation_test.go
  model/cluster_test.go
  model/group.go
  model/group_test.go
  model/webhook_test.go
Labels: 3: Reviews Complete, kind/bug, release-note

#202 MM-24209: added support to create and tear down encryption keys with leaking resources
  Makefile
  internal/mocks/aws-sdk/resource_tagging.go
  internal/testlib/aws.go
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/constants.go
  internal/tools/aws/database.go
  internal/tools/aws/database_test.go
  internal/tools/aws/helpers.go
  internal/tools/aws/kms.go
  internal/tools/aws/rds.go
  internal/tools/aws/resource_tagging.go
  internal/tools/aws/resource_tagging_test.go
Labels: 2: Dev Review, kind/bug, release-note

#205 MM-24373 Add --dev flag to enable development mode
  cmd/cloud/server.go
Labels: 3: Reviews Complete, release-note

#207 add job to notify releases into a Mattermost channel
  .github/workflows/notify-release.yml
Labels: 3: Reviews Complete, kind/documentation, kind/feature, release-note-none

#204 MM-23741 Only run Helm once during install
  internal/provisioner/certmanager.go
  internal/provisioner/fluentbit.go
  internal/provisioner/helm_utils.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/public_nginx.go
  internal/provisioner/utility_group.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
Labels: 3: Reviews Complete, release-note
