Repository mattermost/mattermost-cloud, pull requests merged in 2020-09, with the labels that each got.

#299 Add new container exec API endpoint
  cmd/cloud/cluster_installation.go
  internal/api/cluster_installation.go
  internal/api/cluster_installation_test.go
  internal/api/common_test.go
  internal/api/context.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  model/client.go
  model/cluster_installation_request.go
  model/exec.go
Labels: 4: Reviews Complete, kind/feature, release-note

#301 Fix master count value CLI typo
  cmd/cloud/cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#302 Fix master instance type value CLI typo
  cmd/cloud/cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#303 [MM-28321] Increasing the Prometheus persistent volume to 100Gi from 8Gi
  helm-charts/prometheus_values.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#300 add white-list cidrs to internal ingress for prometheus
  README.md
  cmd/cloud/server.go
  helm-charts/nginx_values.yaml
  internal/api/request_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/prometheus.go
  model/cluster_utility.go
Labels: 4: Reviews Complete, kind/bug, kind/feature, priority/important-soon, release-note

#305 Check more than state on reconciling cluster installations
  internal/supervisor/cluster_installation.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#304 Update README
  README.md
Labels: 4: Reviews Complete, release-note-none

#306 Add S3 Multitenant Filestore
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/teleport.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/filestore.go
  internal/tools/aws/filestore_multitenant.go
  internal/tools/aws/filestore_test.go
  internal/tools/aws/helpers.go
  internal/tools/aws/iam.go
  internal/tools/aws/s3.go
  internal/tools/aws/session.go
  internal/tools/utils/utils.go
  model/installation_filestore.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#307 Update mattermost-operator
  go.mod
  go.sum
  internal/mocks/aws-sdk/ec2.go
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, kind/cleanup, kind/feature, release-note-none

#308 MM-27476 Improve DNS hostname validation
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, release-note

#309 Add table output option for resource lists
  cmd/cloud/cluster.go
  cmd/cloud/cluster_installation.go
  cmd/cloud/group.go
  cmd/cloud/installation.go
  cmd/cloud/webhook.go
  go.mod
  go.sum
Labels: 4: Reviews Complete, kind/feature, release-note

#311 Release operator version v1.8.0
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#310 MM-16248 Add a health check to Provisioner start-up
  cmd/cloud/server.go
Labels: 4: Reviews Complete, release-note

#314 Remove bucket name startup check
  cmd/cloud/server.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#313 Add read replica configuration to installations
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/helpers.go
Labels: 4: Reviews Complete, kind/feature, release-note
