Repository mattermost/mattermost-cloud, pull requests merged in 2020-06, with the labels that each got.

#228 Graceful SIGTERM shutdown
  cmd/cloud/server.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/doer.go
  internal/supervisor/doer_test.go
  internal/supervisor/group.go
  internal/supervisor/installation.go
  internal/supervisor/scheduler.go
Labels: 2: Infra Review, kind/bug, release-note

#230 Update kops to 1.16.3
  Makefile
Labels: 4: Reviews Complete, kind/feature, release-note

#231 The versioning for kops now includes a `v` prefix
  Makefile
Labels: 4: Reviews Complete, kind/regression, release-note

#232 helm: bump helm to v2.16.6
  Makefile
Labels: kind/cleanup, priority/critical-urgent, release-note

#236 Refactor cluster metadata handling
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_utils.go
  internal/store/cluster.go
  internal/store/cluster_test.go
  internal/store/installation.go
  internal/store/migrations.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
  model/aws_metadata.go
  model/aws_metadata_test.go
  model/cluster.go
  model/cluster_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
  model/kops_metadata.go
  model/kops_metadata_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#237 server: add missing syscal to trap the shutdown
  build/Dockerfile
  cmd/cloud/server.go
Labels: 4: Reviews Complete, kind/feature, priority/important-soon, release-note

#238 ci: retry docker push if fails in the first attempt
  .circleci/config.yml
  hacks/push-docker-pr.sh
  hacks/push-docker.sh
Labels: 4: Reviews Complete, kind/cleanup, release-note

#233 MM-24192 Adding Teleport utility group
  cmd/cloud/cluster.go
  helm-charts/teleport_values.yaml
  internal/api/request_test.go
  internal/provisioner/teleport.go
  internal/provisioner/utility_group.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/iam.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Infra Review, kind/feature, release-note

#234 dependencies: some dependencies update
  go.mod
  go.sum
Labels: 2: Infra Review, kind/cleanup, release-note

#240 Bump helm version and correct README
  Makefile
  README.md
Labels: 2: Dev Review, 2: Infra Review, kind/documentation, release-note

#220 netpol: install calico to implement network policies
  build/Dockerfile
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/tools/k8s/daemonset.go
  internal/tools/k8s/daemonset_test.go
  internal/tools/k8s/helpers.go
  internal/tools/k8s/helpers_test.go
  internal/tools/k8s/manifest.go
  internal/tools/k8s/manifest_test.go
  internal/tools/k8s/namespaces.go
  internal/tools/k8s/namespaces_test.go
  internal/tools/k8s/networkpolicy.go
  internal/tools/k8s/networkpolicy_test.go
  internal/tools/k8s/poddisruptionbudget.go
  internal/tools/k8s/poddisruptionbudget_test.go
  internal/tools/k8s/roles.go
  internal/tools/k8s/roles_test.go
  manifests/calico-policy-only.yaml
  manifests/network-policies/mm-installation-netpol.yaml
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_example.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermostrestoredb_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_restoredb_example.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
  manifests/operator-manifests/mattermost/role_binding.yaml
  manifests/operator-manifests/mattermost/service_account.yaml
  manifests/operator-manifests/minio/minio-operator.yaml
  manifests/operator-manifests/mysql/mysql-operator.yaml
Labels: 4: Reviews Complete, kind/feature, priority/important-soon, release-note

#242 small fix
  internal/api/cluster.go
Labels: release-note-none

#243 add build hash info when start the server
  Makefile
  cmd/cloud/server.go
  model/version.go
Labels: 4: Reviews Complete, kind/feature, release-note

#247 update helm / alpine and go
  Makefile
  build/Dockerfile
Labels: 4: Reviews Complete, kind/cleanup, release-note

#245 Set logging output default to stdout
  cmd/cloud/logger.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#246 Add installation hibernation
  cmd/cloud/installation.go
  internal/api/installation.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  model/client.go
  model/installation_states.go
Labels: 4: Reviews Complete, kind/feature, release-note

#250 dependencies: update several dependencies
  go.mod
  go.sum
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/iam.go
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/resource_tagging.go
  internal/mocks/aws-sdk/route53.go
  internal/mocks/aws-sdk/s3.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/mocks/aws-tools/client.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#235 MM-25481: enable TLS connection between services and RDS databases
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/helpers.go
Labels: 4: Reviews Complete, release-note

#241 validate if the request has spaces in some fields
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, kind/bug, priority/important-soon, release-note

#251 Add cluster workbench command for cloud client
  cmd/cloud/main.go
  cmd/cloud/workbench.go
  internal/tools/kops/cmd.go
Labels: 4: Reviews Complete, kind/feature, release-note

#229 Creating an additional output field in fluent-bit for security audit logs
  go.mod
  go.sum
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/iam.go
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/resource_tagging.go
  internal/mocks/aws-sdk/route53.go
  internal/mocks/aws-sdk/s3.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/mocks/aws-tools/client.go
  internal/mocks/logger/logrus.go
  internal/provisioner/fluentbit.go
  internal/provisioner/fluentbit_test.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/route53.go
Labels: release-note

#255 Move contents of terraform state file to Go constant
  build/Dockerfile
  internal/tools/terraform/plan.go
  internal/tools/terraform/state.go
  terraform/backend.tf
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#258 Add cloud webhook listener (cwl)
  cmd/tools/README.md
  cmd/tools/cwl/cwl.go
Labels: 4: Reviews Complete, release-note-none

#256 public-nginx: remove nginx version from the responses
  helm-charts/public-nginx_values.yaml
Labels: 4: Reviews Complete, kind/cleanup, release-note

#257 Cleanup multitenant database logging
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/multitenant_database_test.go
  internal/tools/aws/acm_test.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/ec2.go
  internal/tools/aws/rds_test.go
  internal/tools/aws/route53_test.go
  model/multitenant_database.go
  model/multitenant_database_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note
