Repository mattermost/mattermost-cloud, pull requests merged in 2020-10, with the labels that each got.

#312 MM-27129 - Add group status endpoint
  .gitignore
  cmd/cloud/group.go
  internal/api/context.go
  internal/api/group.go
  internal/api/group_test.go
  internal/store/group.go
  internal/store/group_test.go
  model/client.go
  model/group_status.go
  model/group_status_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#315 add installation dns in the webhook payload for the installations
  internal/api/installation.go
  internal/supervisor/installation.go
Labels: 4: Reviews Complete, kind/cleanup, release-note-none

#318 update the api url to have the correct url as example
  internal/api/security.go
Labels: kind/cleanup, release-note-none

#316 [MM 29112] Migrating to Prometheus operator and enabling Thanos sidecar.
  cmd/cloud/cluster.go
  go.mod
  helm-charts/prometheus_operator_values.yaml
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/fluentbit.go
  internal/provisioner/helm_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/teleport.go
  internal/provisioner/utility_group.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#323 Update cluster installation secrets on installation update
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 4: Reviews Complete, kind/feature, release-note

#319 kops: validate AMI image before running the upgrade k8s cluster
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
Labels: 4: Reviews Complete, kind/cleanup, kind/feature, release-note

#325 Mattermost operator 1.9.0 release
  go.mod
  go.sum
  internal/mocks/model/installation_database.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/group_test.go
  internal/store/installation_test.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/group_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/filestore.go
  internal/tools/aws/filestore_multitenant.go
  k8s/custom_resources.go
  k8s/custom_resources_test.go
  k8s/manifest.go
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  model/installation_database.go
  model/installation_filestore.go
  model/installation_request.go
  model/installation_states.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#326 [MM-29639] Adding Prometheus service monitors for Mattermost and NGINX metrics
  helm-charts/prometheus_operator_values.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#322 [MM-28659] Introducing Thanos utility group
  cmd/cloud/cluster.go
  helm-charts/thanos_values.yaml
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/kops_utils.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Infra Review, kind/feature, release-note

#324 MM-29005 - Migrate to Helm 3 for provisioning utility group
  Makefile
  README.md
  build/Dockerfile
  cmd/cloud/server.go
  helm-charts/prometheus_operator_values.yaml
  helm-charts/thanos_values.yaml
  internal/provisioner/fluentbit.go
  internal/provisioner/helm2_utils.go
  internal/provisioner/helm_migrate.go
  internal/provisioner/helm_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  internal/tools/helm/cmd.go
  internal/tools/helm/commands.go
Labels: 4: Reviews Complete, release-note

#321 MM-29236 - Introduce Cluster and Installation Annotations
  cmd/cloud/cluster.go
  cmd/cloud/installation.go
  internal/api/cluster.go
  internal/api/cluster_installation_test.go
  internal/api/cluster_test.go
  internal/api/context.go
  internal/api/group_test.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/api/lock.go
  internal/store/annotation.go
  internal/store/annotation_test.go
  internal/store/cluster.go
  internal/store/cluster_dto.go
  internal/store/cluster_dto_test.go
  internal/store/cluster_test.go
  internal/store/group_test.go
  internal/store/installation.go
  internal/store/installation_dto.go
  internal/store/installation_dto_test.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/store/store.go
  internal/store/testing.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/cluster_test.go
  internal/supervisor/group_test.go
  internal/supervisor/installation_test.go
  model/annotation.go
  model/annotation_test.go
  model/client.go
  model/cluster.go
  model/cluster_dto.go
  model/cluster_dto_test.go
  model/cluster_request.go
  model/group_status_test.go
  model/installation.go
  model/installation_dto.go
  model/installation_dto_test.go
  model/installation_request.go
Labels: 4: Reviews Complete, release-note

#328 Fix build of Provisioner
  internal/store/installation_dto_test.go
Labels: 4: Reviews Complete, release-note-none

#329 Add cloud dashboard command
  cmd/cloud/dashboard.go
  cmd/cloud/main.go
  go.mod
  go.sum
  internal/api/group_test.go
  internal/store/group.go
  internal/store/group_test.go
  model/group_status.go
  model/group_status_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#327 Handle group updates during installation rollouts
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/supervisor/group.go
  internal/supervisor/group_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/common_test.go
  model/installation.go
  model/installation_states.go
  model/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#331 Fix tests related to annotation changes
  internal/supervisor/installation_test.go
Labels: 4: Reviews Complete, release-note-none

#333 Use correct DB reader endpoints for multitenant databases
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/helpers.go
Labels: 4: Reviews Complete, kind/bug, release-note

#334 Handle group configuration changes on installation creation
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: kind/bug, release-note

#335 Handle multitenant filestore teardown with no cluster installations
  internal/tools/aws/filestore_multitenant.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#332 Add group no-op update sequence bump option
  cmd/cloud/group.go
  internal/api/group_test.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/group.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/group_request.go
  model/group_request_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#330 MM-29237 - Schedule Installations based on Annotations
  cmd/cloud/cluster.go
  cmd/cloud/installation.go
  docs/annotations.md
  internal/api/cluster_test.go
  internal/api/installation_test.go
  internal/store/annotation.go
  internal/store/cluster.go
  internal/store/cluster_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/annotation_test.go
  model/cluster.go
  model/cluster_request.go
  model/installation_request.go
Labels: 4: Reviews Complete, release-note

#339 Set HOME dir for Helm 3
  build/Dockerfile
Labels: release-note-none

#341 Revert last PR that introduced HOME /root. Will be added in the next PR with some other changes.
  build/Dockerfile
Labels: release-note-none

#338 Refactor AWS database connection string logic
  internal/tools/aws/constants.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/helpers.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#342 Do not cleanup Helm 2 directory
  internal/provisioner/helm_migrate.go
  internal/provisioner/helm_utils.go
Labels: release-note-none

#343 Increase timeout on Helm upgrade
  internal/provisioner/helm_utils.go
Labels: release-note-none

#344 add error message in the log
  internal/supervisor/installation.go
Labels: kind/cleanup, release-note-none

#336 Add endpoints to modify annotations on existing Clusters and Installations
  cmd/cloud/cluster.go
  cmd/cloud/cluster_annotation.go
  cmd/cloud/installation.go
  cmd/cloud/installation_annotation.go
  docs/annotations.md
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/annotation.go
  internal/store/annotation_test.go
  internal/store/cluster_installation.go
  internal/store/store.go
  model/annotation.go
  model/annotation_test.go
  model/client.go
Labels: release-note

#346 Migrating to new stable chart repo and removing unused metrics.
  helm-charts/prometheus_operator_values.yaml
  internal/provisioner/utility_group.go
Labels: release-note-none

#347 Add test suite tool
  cmd/tools/ctest/ctest.go
  cmd/tools/ctest/logger.go
  cmd/tools/ctest/main.go
Labels: 4: Reviews Complete, kind/feature, release-note
