Repository mattermost/mattermost-cloud, pull requests merged in 2020-01, with the labels that each got.

#128 Refactor CreateClusterRequest
  internal/api/request_test.go
  model/cluster_request.go
  model/cluster_request_test.go
Labels: 2: Dev Review

#126 Add a make install build target
  Makefile
Labels: 3: Reviews Complete

#131 Update alpine image and add new terraform folder
  build/Dockerfile
Labels: 3: Reviews Complete

#127 Clean up transitionClusterInstallation
  internal/supervisor/cluster_installation.go
Labels: 2: Dev Review, 3: Reviews Complete

#132 Add CreateInstallationRequest Testing
  internal/tools/aws/cluster_management.go
  model/installation_request_test.go
Labels: 3: Reviews Complete

#133 Log terraform match error and proceed on cluster deletion
  internal/provisioner/kops_provisioner_cluster.go
Labels: 3: Reviews Complete

#125 MM-21091: look up hosted zone ids and certificate ARN in AWS when flags are not supplied
  README.md
  cmd/cloud/server.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/acm.go
  internal/tools/aws/acm_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/database.go
  internal/tools/aws/ec2_test.go
  internal/tools/aws/filestore.go
  internal/tools/aws/route53.go
  internal/tools/aws/route53_test.go
Labels: 3: Reviews Complete

#136 check if the AWS AMI exists before create the k8s cluster
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/ec2.go
  internal/tools/aws/ec2_test.go
  internal/tools/aws/mock.go
Labels: 3: Reviews Complete

#138 Fix VPC claim count check
  internal/tools/aws/cluster_management.go
Labels: 2: Dev Review

#130 Defining an interface for managing cluster utilities as a group
  internal/provisioner/fluentbit.go
  internal/provisioner/helm_utils.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/utility_group.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
Labels: 2: Infra Review

#137 Gracefully succeed if S3 bucket is already deleted
  internal/tools/aws/filestore.go
  internal/tools/aws/s3.go
Labels: 3: Reviews Complete

#134 MM-21259 Tag VPCs with Human Owner's Name
  cmd/cloud/server.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/constants.go
  internal/tools/aws/ec2_test.go
Labels: 2: Dev Review

#139 Remove DNS records regardless of their length during deletion
  internal/tools/aws/route53.go
Labels: 2: Dev Review, 2: Infra Review

#140 Improved cluster delete logic
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/cluster_management.go
Labels: 3: Reviews Complete

#142 Remove deprecated flags
  cmd/cloud/server.go
  kubernetes/deployment.yaml
  kubernetes/pvc.yaml
  kubernetes/secrets.yaml
Labels: 3: Reviews Complete

#147 Bump Mattermost operator version to v1.1.0
  operator-manifests/mattermost/operator.yaml
Labels: 2: Dev Review, 2: Infra Review

#145 add Https status and write the header in the correct order
  internal/api/cluster.go
  internal/api/cluster_installation.go
  internal/api/group.go
  internal/api/installation.go
  internal/api/webhook.go
  model/client.go
Labels: 2: Dev Review

#146 Lookup private AWS hosted zone domain name
  cmd/cloud/server.go
  internal/provisioner/fluentbit.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/nginx.go
  internal/provisioner/prometheus.go
  internal/provisioner/utility_group.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
Labels: 3: Reviews Complete
