Repository mattermost/mattermost-cloud, pull requests merged in 2020-08, with the labels that each got.

#280 fix region for S3 endpoint
  internal/tools/aws/filestore.go
Labels: 4: Reviews Complete, kind/bug, release-note-none

#278 [MM 27287] Add support for Teleport external storage and HA deployment.
  internal/api/request_test.go
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/dynamodb.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/teleport.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/dynamodb.go
  internal/tools/aws/filestore.go
  internal/tools/aws/s3.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#281 Add cloud resource API security locking
  cmd/cloud/cluster.go
  cmd/cloud/cluster_installation.go
  cmd/cloud/group.go
  cmd/cloud/installation.go
  cmd/cloud/main.go
  cmd/cloud/security.go
  cmd/cloud/server.go
  cmd/cloud/webhook.go
  cmd/cloud/workbench.go
  internal/api/api.go
  internal/api/cluster.go
  internal/api/cluster_installation.go
  internal/api/cluster_installation_test.go
  internal/api/cluster_test.go
  internal/api/context.go
  internal/api/group.go
  internal/api/group_test.go
  internal/api/helpers.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/api/security.go
  internal/store/cluster.go
  internal/store/cluster_installation.go
  internal/store/group.go
  internal/store/installation.go
  internal/store/migrations.go
  model/client.go
  model/cluster.go
  model/cluster_installation.go
  model/cluster_request.go
  model/group.go
  model/group_request.go
  model/installation.go
  model/installation_request.go
Labels: 4: Reviews Complete, kind/feature, release-note

#283 Add PostgreSQL Multitenant Database option
  cmd/cloud/server.go
  go.mod
  go.sum
  internal/mocks/model/installation_database.go
  internal/store/group.go
  internal/store/migrations.go
  internal/store/multitenant_database.go
  internal/store/multitenant_database_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client_test.go
  internal/tools/aws/constants.go
  internal/tools/aws/database.go
  internal/tools/aws/database_migration.go
  internal/tools/aws/database_migration_test.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/helpers.go
  internal/tools/aws/rds.go
  internal/tools/utils/utils.go
  model/installation_database.go
  model/multitenant_database.go
  model/multitenant_database_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#284 Shorten database username for Mattermost installations
  internal/tools/aws/database_multitenant.go
Labels: 4: Reviews Complete, kind/bug, release-note

#285 Add nginx utility check for ACM resources
  internal/provisioner/nginx.go
  internal/tools/utils/utils.go
  model/installation_database.go
Labels: 2: Dev Review, kind/bug, release-note

#279 k8s: if pod is not found continue the check and assume that was part of the old replicaset
  internal/provisioner/kops_provisioner_cluster.go
  k8s/helpers.go
  k8s/helpers_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#286 Add API to list multitenant databases
  cmd/cloud/databases.go
  cmd/cloud/main.go
  internal/api/api.go
  internal/api/context.go
  internal/api/databases.go
  internal/api/helpers.go
  model/client.go
  model/multitenant_database.go
  model/multitenant_database_request.go
Labels: 4: Reviews Complete, kind/feature, release-note

#288 Add dry-run flag for cluster CLI commands
  cmd/cloud/cluster.go
Labels: 4: Reviews Complete, kind/feature, release-note

#289 Log installation size resource requirements
  internal/supervisor/installation.go
Labels: 4: Reviews Complete, release-note

#287 k8s/namespace: when deleting the namespace make sure everything gets deleted as well
  k8s/namespaces.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#291 GetInstallationsByDNS is returning error if length is 0
  internal/api/installation_test.go
  model/client.go
Labels: 4: Reviews Complete, release-note-none

#292 Installations count endpoint
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  model/client.go
  model/installation.go
Labels: 4: Reviews Complete, release-note

#294 drop requests to prometheus ingress if is not using the dns name
  helm-charts/nginx_values.yaml
  internal/provisioner/prometheus.go
Labels: 4: Reviews Complete, kind/bug, release-note

#296 Revert "drop requests to prometheus ingress if is not using the dns name"
  helm-charts/nginx_values.yaml
  internal/provisioner/prometheus.go
Labels: release-note-none

#295 Add dry-run flag for installation and group CLI commands
  cmd/cloud/group.go
  cmd/cloud/installation.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#297 Fixing ctx timing to make sure that Nginx load balancer services are in place for Prometheus Route53 registration.
  internal/provisioner/kops_utils.go
  internal/provisioner/prometheus.go
Labels: 4: Reviews Complete, kind/bug, priority/critical-urgent, release-note

#293 Enable default AWS S3 SSE
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/tools/aws/s3.go
Labels: 4: Reviews Complete, kind/feature, release-note

#298 Include instruction on how to create the s3 bucket
  README.md
Labels: release-note-none
