Repository mattermost/mattermost-cloud, pull requests merged in 2021-09, with the labels that each got.

#515 MM-32272 Update default Fluentbit version
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#516 Refactor proxy database resource records
  internal/mocks/model/installation_database.go
  internal/provisioner/pgbouncer.go
  internal/store/db_database_schema.go
  internal/store/db_database_schema_test.go
  internal/store/db_helpers.go
  internal/store/db_helpers_test.go
  internal/store/db_logical_database.go
  internal/store/db_logical_database_test.go
  internal/store/db_multitenant_database.go
  internal/store/db_multitenant_database_test.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation_test.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  model/installation.go
  model/installation_database.go
  model/multitenant_database.go
Labels: 4: Reviews Complete, kind/design, release-note

#517 Bump thanos to helm chart 5.2.1
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Infra Review, release-note, kind/chore

#518 Update Prometheus chart version to 18.0.3
  internal/api/cluster_test.go
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Infra Review, kind/feature, release-note, kind/chore

#519 Add ability to specify custom columns to table output
  cmd/cloud/backup.go
  cmd/cloud/cluster.go
  cmd/cloud/cluster_installation.go
  cmd/cloud/installation.go
  cmd/cloud/installation_operation_db_migration.go
  cmd/cloud/installation_operation_restoration.go
  cmd/cloud/table_printer.go
  cmd/cloud/table_printer_test.go
Labels: kind/feature, release-note

#522 update fluent-bit chart version to 0.16.6
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Infra Review, release-note, kind/chore

#520 Add server flag to configure max installation schemas
  cmd/cloud/server.go
  internal/tools/aws/constants.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  model/multitenant_database.go
Labels: 2: Infra Review, kind/feature, release-note

#525 Remove alerting block from installation SLIs
  internal/provisioner/kops_provisioner_installation_sli.go
Labels: release-note, kind/refactor

#524 Add database resource list and get API endpoints
  cmd/cloud/databases.go
  cmd/cloud/installation.go
  internal/api/databases.go
  internal/api/db_database_schema.go
  internal/api/db_database_schema_test.go
  internal/api/db_logical_database.go
  internal/api/db_logical_database_test.go
  internal/api/db_multitenant_database.go
  internal/api/db_multitenant_database_test.go
  internal/api/group_test.go
  internal/api/helpers.go
  internal/mocks/model/installation_database.go
  internal/store/db_database_schema.go
  internal/supervisor/installation_test.go
  model/client.go
  model/installation_database.go
  model/multitenant_database.go
  model/multitenant_database_request.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#529 BugFix: Disabling Sloth Alerting
  internal/provisioner/kops_provisioner_installation_sli.go
Labels: kind/bug, release-note

#526 Fix listing kops clusters if there is only one or none clusters
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_test.go
  internal/tools/kops/cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#530 Installation removal fix for pgbouncer resource records
  internal/store/db_helpers.go
  internal/store/db_helpers_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#513 mm-37913-avoid-reprovisioning-calico-cni
  internal/provisioner/kops_provisioner_cluster.go
Labels: 4: Reviews Complete, release-note

#531 Add database cmd table options
  cmd/cloud/databases.go
Labels: 4: Reviews Complete, kind/feature, release-note

#532 Bump Go and Alpine versions
  Makefile
  build/Dockerfile
Labels: 4: Reviews Complete, kind/cleanup, release-note-none

#523 Fix inheriting desired Utilities from actual
  internal/api/cluster.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, kind/bug, release-note

#521 Introduce Resource interface and code generation to Provisioner
  Makefile
  cmd/provisioner-code-gen/generate.go
  cmd/provisioner-code-gen/generate_test.go
  cmd/provisioner-code-gen/main.go
  cmd/provisioner-code-gen/testdata/all_generators.txt
  cmd/provisioner-code-gen/testdata/id_generator.txt
  cmd/provisioner-code-gen/testdata/test_structs.go
  cmd/provisioner-code-gen/util.go
  cmd/tools/testwick/wicker/mocks/testwicker.go
  go.mod
  go.sum
  hack/boilerplate/boilerplate.py
  model/cluster.go
  model/cluster_gen.go
  model/installation.go
  model/installation_gen.go
  model/provisioner_resource.go
Labels: 4: Reviews Complete, kind/feature, release-note

#527 Add nginx endpoints for kubecost
  internal/provisioner/kubecost.go
  internal/provisioner/utility_group.go
Labels: kind/feature, release-note

#533 Fix for collecting kops node instance types
  internal/tools/kops/instance_groups.go
  model/kops_metadata.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#534 Installation weight calculation fix for zero installations
  internal/store/installation.go
  internal/store/installation_test.go
Labels: 4: Reviews Complete, kind/bug, release-note

#535 Check for nil DB resources when generating database resources
  internal/tools/aws/database_multitenant_pgbouncer.go
Labels: 4: Reviews Complete, kind/bug, release-note

#540 [MM-38377] Add svc for Calico felix metrics
  manifests/calico-cni.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#537 Bump kubecost version to 1.86.1
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note, kind/chore

#542 MM-38760 Upgrade Fluent-bit helm chart version to 0.17.0
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 4: Reviews Complete, kind/feature, release-note, kind/chore

#543 Add desktop notifications to Cloud Webhook Listener
  cmd/tools/cwl/cwl.go
  cmd/tools/cwl/profile.png
  go.mod
  go.sum
Labels: 2: Dev Review, kind/feature, release-note

#539 Create initial end-to-end tests for cluster lifecycle
  Makefile
  README.md
  e2e/pkg/cluster.go
  e2e/pkg/installation.go
  e2e/pkg/installation_builder.go
  e2e/pkg/k8s.go
  e2e/pkg/webhook_handler.go
  e2e/tests/cluster/cluster_test.go
  e2e/tests/cluster/steps.go
  e2e/tests/cluster/suite.go
  e2e/tests/dbmigration/suite.go
  e2e/workflow/cluster.go
  e2e/workflow/db_migration.go
  e2e/workflow/installation.go
Labels: 4: Reviews Complete, kind/feature, release-note

#544 [MM-38756] Upgrade Stackrox version to 65.1.0
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#541 Retry to create channels to avoid conflicting names
  cmd/tools/testwick/go.mod
  cmd/tools/testwick/go.sum
  cmd/tools/testwick/main.go
  cmd/tools/testwick/wicker/names.go
  cmd/tools/testwick/wicker/testwicker.go
  cmd/tools/testwick/wicker/testwicker_test.go
Labels: kind/bug, release-note
