Repository mattermost/mattermost-cloud, pull requests merged in 2021-01, with the labels that each got.

#390 MM-31627 - Add network policy for installations with beta spec
  k8s/networkpolicy.go
  manifests/network-policies/mm-installation-netpol.yaml
Labels: release-note

#391 Increase max DB installations to 300
  internal/tools/aws/constants.go
Labels: 4: Reviews Complete, release-note

#393 Update retention period to 2d for Prometheus local stored data.
  helm-charts/prometheus_operator_values.yaml
Labels: release-note

#394 Hibernate prometheus_adapter
  manifests/prometheus-adapter/prometheus-adapter.yaml
Labels: release-note-none

#395 Add weight for nodeaffinity
  manifests/prometheus-adapter/prometheus-adapter.yaml
Labels: release-note

#396 Remove prometheus-adapter temporary.
  internal/provisioner/kops_provisioner_cluster.go
  manifests/prometheus-adapter/prometheus-adapter.yaml
Labels: release-note-none

#398 [MM 32004] Release Mattermost Operator v1.12.0
  go.mod
  go.sum
  internal/provisioner/kops_provisioner_cluster.go
  k8s/manifest.go
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermost_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
Labels: 4: Reviews Complete, release-note

#397 MM-30849 - Preserve order of Env variables to not to trigger installation rollout
  model/env.go
Labels: 4: Reviews Complete, release-note

#371 split nginx deployments in two
  cmd/cloud/cluster.go
  helm-charts/nginx_internal_values.yaml
  helm-charts/nginx_values.yaml
  helm-charts/prometheus_operator_values.yaml
  helm-charts/thanos_values.yaml
  internal/api/request_test.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  model/cluster_request.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, priority/important-soon, release-note

#399 Nginx fix to redirect to SSL and use X-Real-IP
  helm-charts/nginx_values.yaml
Labels: 2: Dev Review, 2: Infra Review, release-note

#392 MM-31627 - Support Operator Beta spec Custom Resource in Provisioner
  internal/api/installation.go
  internal/api/installation_test.go
  internal/mocks/model/installation_database.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/filestore.go
  internal/tools/aws/filestore_bifrost.go
  internal/tools/aws/filestore_multitenant.go
  k8s/client.go
  k8s/client_test.go
  k8s/custom_resources.go
  k8s/networkpolicy.go
  model/installation.go
  model/installation_database.go
  model/installation_filestore.go
  model/single_tenant_database.go
  model/single_tenant_database_test.go
Labels: 4: Reviews Complete, release-note

#400 Fix Nginx ingress chart prefix to show correct version in metadata
  internal/provisioner/nginx_internal.go
Labels: kind/bug, release-note

#402 MM-32053 Properly fetch and decode values file from Gitlab API
  internal/provisioner/helm_utils.go
Labels: 2: Infra Review, release-note

#404 [MM 31037] Updating utility default values to meet dev requirements.
  helm-charts/nginx_internal_values.yaml
  helm-charts/nginx_values.yaml
  helm-charts/prometheus_operator_values.yaml
  helm-charts/thanos_values.yaml
Labels: release-note

#403 MM-32264 - Switch Provisioner to use Operator beta CR by default
  internal/store/installation_test.go
  model/installation.go
Labels: 4: Reviews Complete, release-note

#405 Add 'state' as an installation list filter
  cmd/cloud/installation.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  model/installation.go
  model/installation_request.go
Labels: 4: Reviews Complete, kind/feature, release-note

#406 Fix v1alpha1 hibernation replica count check
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 4: Reviews Complete, kind/bug, release-note

#407 Hide installation license value in CLI output
  cmd/cloud/installation.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#408 Fix AMI check and validate kops change requests
  internal/provisioner/kops_provisioner_cluster.go
  model/kops_metadata.go
  model/kops_metadata_test.go
Labels: 4: Reviews Complete, kind/feature, release-note
