Repository mattermost/mattermost-cloud, pull requests merged in 2021-04, with the labels that each got.

#438 [MM-34083] Fix CLRF vulnerability in wakeup redirect
  helm-charts/nginx_values.yaml
Labels: 2: Dev Review, release-note

#430 Add k8s-spot-termination-handler Daemonset
  internal/provisioner/kops_provisioner_cluster.go
  manifests/k8s-spot-termination-handler/k8s-spot-termination-handler.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#442 Add group ID env var to installations for use with feature flags
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 2: Dev Review, release-note

#440 MM-34126 - Add restoration job handling to Provisioner
  internal/provisioner/backup_restore.go
  internal/provisioner/backup_restore_test.go
  internal/provisioner/kops_provisioner_backup_restore.go
Labels: release-note

#441 Refactor state transitions validation
  model/cluster_states.go
  model/cluster_states_test.go
  model/installation_backup.go
  model/installation_states.go
  model/installation_states_test.go
Labels: 4: Reviews Complete, release-note-none

#443 Implement Installation DB restoration model
  internal/api/installation_backup.go
  internal/store/installation.go
  internal/store/installation_db_restoration_operation.go
  internal/store/installation_db_restoration_operation_test.go
  internal/store/migrations.go
  internal/supervisor/backup.go
  model/installation_backup.go
  model/installation_backup_test.go
  model/installation_db_restoration_operation.go
  model/installation_db_restoration_operation_test.go
  model/installation_db_restoration_request.go
  model/installation_db_restoration_request_test.go
  model/installation_states.go
Labels: 4: Reviews Complete, kind/feature, release-note

#444 Deploy pgbouncer helm chart as utility
  cmd/cloud/cluster.go
  helm-charts/pgbouncer_values.yaml
  helm-charts/prometheus_operator_values.yaml
  internal/api/request_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/pgbouncer.go
  internal/provisioner/utility_group.go
  internal/tools/aws/database_multitenant.go
  manifests/pgbouncer-manifests/pgbouncer-configmap.yaml
  manifests/pgbouncer-manifests/pgbouncer-secret.yaml
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#447 Bump Bifrost to v1.0.2
  manifests/bifrost/bifrost.yaml
Labels: 4: Reviews Complete, release-note

#448 [MM-35180] Add metrics for fluentbit and upgrade default version.
  helm-charts/fluent-bit_values.yaml
  helm-charts/prometheus_operator_values.yaml
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Infra Review, release-note
