Repository mattermost/mattermost-cloud, pull requests merged in 2021-05, with the labels that each got.

#445 MM 34873 shared vpc feature for kops clusters
  cmd/cloud/cluster.go
  internal/api/cluster.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/nginx.go
  internal/store/cluster.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/constants.go
  internal/tools/aws/filestore_bifrost.go
  internal/tools/aws/helpers.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/cluster_request.go
  model/kops_metadata.go
Labels: 4: Reviews Complete, kind/feature

#446 Add installation restoration supervisor
  cmd/cloud/server.go
  internal/supervisor/backup.go
  internal/supervisor/backup_lock.go
  internal/supervisor/common.go
  internal/supervisor/installation_db_restoration.go
  internal/supervisor/installation_db_restoration_lock.go
  internal/supervisor/installation_db_restoration_test.go
  model/webhook.go
Labels: 4: Reviews Complete, kind/feature, release-note

#439 MM-32293 Integration between Provisioner and AWAT
  cmd/cloud/installation.go
  cmd/cloud/server.go
  go.mod
  go.sum
  internal/mocks/awat/client.go
  internal/mocks/awat/doc.go
  internal/mocks/aws-tools/client.go
  internal/supervisor/import.go
  internal/supervisor/import_test.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/filestore_bifrost.go
  internal/tools/aws/filestore_multitenant.go
  internal/tools/aws/helpers.go
  internal/tools/aws/s3.go
  model/installation_states.go
Labels: 4: Reviews Complete, release-note

#451 Correct the type of the JSON line number returned by Mattermost while checking Import Jobs
  internal/supervisor/import.go
  internal/supervisor/import_test.go
Labels: 2: Dev Review, release-note-none

#449 Add installation database migration model and store
  internal/store/installation_backup.go
  internal/store/installation_backup_test.go
  internal/store/installation_db_migration.go
  internal/store/installation_db_migration_test.go
  internal/store/installation_db_restoration_operation_test.go
  internal/store/migrations.go
  internal/store/multitenant_database.go
  internal/store/multitenant_database_test.go
  internal/store/util.go
  model/installation_db_migration_operation.go
  model/installation_db_migration_operation_test.go
  model/installation_db_migration_request.go
  model/installation_db_migration_request_test.go
  model/installation_db_restoration_operation.go
  model/multitenant_database.go
Labels: 4: Reviews Complete, kind/feature, release-note

#450 Proposal: give the mock packages unique names
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/dynamodb.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/iam.go
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/resource_tagging.go
  internal/mocks/aws-sdk/route53.go
  internal/mocks/aws-sdk/s3.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/mocks/aws-sdk/sts.go
  internal/mocks/aws-tools/client.go
  internal/mocks/aws-tools/doc.go
  internal/mocks/logger/doc.go
  internal/mocks/logger/logrus.go
  internal/mocks/model/doc.go
  internal/mocks/model/installation_database.go
Labels: 4: Reviews Complete, release-note

#452 Fluentbit input db configuration to avoid duplicate logs
  helm-charts/fluent-bit_values.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#454 Introduce components common functionalities package
  internal/api/context.go
  internal/api/installation_backup.go
  internal/api/installation_backup_test.go
  internal/common/error.go
  internal/common/errors_test.go
  internal/common/installation_backup.go
  internal/common/installation_db_migration.go
  internal/common/installation_db_migration_test.go
  internal/common/installation_restoration.go
  internal/common/util.go
  internal/provisioner/backup_restore.go
  model/cluster_states_test.go
  model/installation_states_test.go
Labels: 4: Reviews Complete, release-note

#456 Add installation recovery command
  cmd/cloud/installation.go
  internal/store/cluster_installation.go
  internal/store/installation.go
  internal/tools/aws/secrets_manager.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#457 Create k8s license secrets with unique names
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/provisioner/kops_provisioner_test.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#459 [MM-35908] Release Mattermost operator v1.14.0 in provisioner
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermost_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermostrestoredb_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
  manifests/operator-manifests/mysql/mysql-operator.yaml
Labels: kind/feature, release-note

#458 Implement Installation DB restoration API
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_db_restoration_operation.go
  internal/api/installation_db_restoration_operation_test.go
  model/client.go
Labels: 4: Reviews Complete, kind/feature, release-note

#455 Implement DB Migration supervisor
  go.sum
  internal/common/installation_db_migration_test.go
  internal/mocks/model/installation_database.go
  internal/provisioner/backup_restore.go
  internal/provisioner/backup_restore_test.go
  internal/provisioner/kops_provisioner_backup_restore.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/supervisor/db_migration.go
  internal/supervisor/db_migration_lock.go
  internal/supervisor/db_migration_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/utils/time.go
  internal/tools/utils/utils.go
  model/cluster_states_test.go
  model/installation_database.go
  model/installation_states_test.go
Labels: 4: Reviews Complete, release-note

#462 [MM-36014] Remove ES endpoint configuration to be handled by utility group values externally
  internal/provisioner/fluentbit.go
  internal/provisioner/fluentbit_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note
