Repository mattermost/mattermost-cloud, pull requests merged in 2021-10, with the labels that each got.

#538 MM-38292 adding logic to skip/avoid the already migrated installations
  internal/api/cluster_installation.go
  internal/api/cluster_installation_test.go
  internal/store/cluster_installation.go
  model/client.go
Labels: 4: Reviews Complete, release-note

#545 Reduce logs and set tcp configurations for pgbouncer
  internal/provisioner/pgbouncer.go
  manifests/pgbouncer-manifests/pgbouncer-configmap.yaml
Labels: 2: Infra Review, kind/feature, release-note, hacktoberfest-accepted

#546 Bump kubecost to 1.87.0
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note, hacktoberfest-accepted, kind/chore

#548 Fix configuration settings for pgbouncer
  internal/provisioner/pgbouncer.go
  manifests/pgbouncer-manifests/pgbouncer-configmap.yaml
Labels: 4: Reviews Complete, kind/feature, release-note, hacktoberfest-accepted
