Repository mattermost/mattermost-cloud, pull requests merged in 2021-03, with the labels that each got.

#417 MM-31628 - Implement migration of ClusterInstallations to Mattermost resource
  cmd/cloud/server.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/store/cluster.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: kind/feature, release-note

#424 Add installation status API endpoint
  cmd/cloud/installation.go
  internal/api/cluster_test.go
  internal/api/context.go
  internal/api/group_test.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  model/client.go
  model/group_status.go
  model/installation.go
  model/installation_status.go
Labels: 4: Reviews Complete, kind/feature, release-note

#423 [MM-30932] Adding support for Rotator tool in cluster upgrades.
  .circleci/config.yml
  cmd/cloud/cluster.go
  go.mod
  go.sum
  internal/mocks/aws-sdk/dynamodb.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/s3.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/cluster.go
  model/cluster_request.go
  model/cluster_request_test.go
  model/kops_metadata.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#425 MM-33398 - Integrate backup - model and store
  internal/store/installation_backup.go
  internal/store/installation_backup_test.go
  internal/store/migrations.go
  model/installation_backup.go
  model/installation_backup_request.go
  model/installation_backup_request_test.go
  model/installation_backup_test.go
  model/webhook.go
Labels: 4: Reviews Complete, kind/feature, release-note

#426 Installation database weighting
  internal/api/installation.go
  internal/mocks/model/installation_database.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  model/installation.go
  model/installation_database.go
  model/installation_states.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#427 [MM-33713] Add validation for rotator when using rotator for cluster upgrades via API
  internal/provisioner/kops_provisioner_cluster.go
  model/cluster_request.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#429 Add bifrost metric monitoring
  helm-charts/prometheus_operator_values.yaml
  manifests/bifrost/bifrost.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#428 MM 33398 - Implement Backup supervisor
  cmd/cloud/server.go
  internal/provisioner/backup_restore.go
  internal/provisioner/backup_restore_test.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_backup_restore.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_test.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/thanos.go
  internal/supervisor/backup.go
  internal/supervisor/backup_lock.go
  internal/supervisor/backup_test.go
  internal/testutil/backup.go
  manifests/bifrost/bifrost.yaml
  model/installation_backup.go
Labels: 4: Reviews Complete, kind/feature, release-note

#431 Update kOps and other tooling
  .circleci/config.yml
  Makefile
  README.md
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/kops/cluster.go
  internal/tools/kops/export.go
  internal/tools/kops/instance_groups.go
  model/kops_metadata.go
  model/kops_metadata_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#432 MM-33398 - Installation backup API
  cmd/cloud/backup.go
  cmd/cloud/installation.go
  cmd/cloud/security.go
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_backup.go
  internal/api/installation_backup_test.go
  internal/api/installation_test.go
  internal/api/lock.go
  internal/api/security.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/backup_restore.go
  internal/store/installation_backup.go
  internal/store/installation_backup_test.go
  internal/supervisor/backup.go
  internal/supervisor/backup_lock.go
  internal/supervisor/backup_test.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/s3.go
  internal/tools/utils/time.go
  model/client.go
  model/installation_backup.go
Labels: 4: Reviews Complete, kind/feature, release-note

#434 Handle case when migration not started yet
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
Labels: kind/bug, release-note

#436 [MM-34265] Update utility values for dev to use new utilities node group.
  helm-charts/prometheus_operator_values.yaml
  helm-charts/teleport_values.yaml
  helm-charts/thanos_values.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#437 Respect installation weights when querying multi tenant databases
  internal/store/multitenant_database.go
  internal/store/multitenant_database_test.go
Labels: kind/bug, release-note

#435 MM 33568 adding multiple cni support
  README.md
  cmd/cloud/cluster.go
  internal/api/cluster.go
  internal/api/request_test.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/cluster.go
  model/cluster_request.go
  model/kops_metadata.go
Labels: 4: Reviews Complete, kind/feature, release-note
