Repository mattermost/mattermost-cloud, pull requests merged in 2021-07, with the labels that each got.

#469 Add CLI commands for migration and restoration
  cmd/cloud/backup.go
  cmd/cloud/installation.go
  cmd/cloud/installation_operation.go
  cmd/cloud/installation_operation_db_migration.go
  cmd/cloud/installation_operation_restoration.go
  cmd/cloud/server.go
  cmd/cloud/utils.go
Labels: 4: Reviews Complete, kind/feature, release-note

#468 Mm 35023 mm apps migration v1
  cmd/cloud/cluster_installation.go
  cmd/cloud/server.go
  internal/api/cluster_installation.go
  internal/api/cluster_installation_test.go
  internal/api/context.go
  internal/mocks/aws-tools/client.go
  internal/store/cluster_installation.go
  internal/store/cluster_installation_test.go
  internal/store/installation.go
  internal/store/migrations.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  model/client.go
  model/cluster_installation.go
  model/cluster_installation_request.go
Labels: 4: Reviews Complete, kind/feature, release-note

#474 Fix operator unit test failures
  internal/api/cluster_installation_test.go
Labels: kind/bug, release-note-none

#472 Add PGBouncer installation databases
  cmd/tools/ctest/database.go
  cmd/tools/ctest/main.go
  go.mod
  go.sum
  internal/mocks/aws-tools/client.go
  internal/mocks/model/installation_database.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/pgbouncer.go
  internal/store/migrations.go
  internal/store/multitenant_database.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/helpers.go
  internal/tools/aws/helpers_sql.go
  internal/tools/aws/secrets_manager.go
  internal/tools/utils/utils.go
  manifests/pgbouncer-manifests/pgbouncer-configmap.yaml
  model/installation_database.go
  model/installation_database_test.go
  model/multitenant_database.go
  model/multitenant_database_states.go
Labels: 4: Reviews Complete, kind/feature, release-note

#460 Adds variables to handle spot-instances notifications
  cmd/cloud/cluster.go
  cmd/cloud/server.go
  internal/api/cluster.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/iam.go
  k8s/helpers.go
  manifests/k8s-spot-termination-handler/k8s-spot-termination-handler.yaml
  model/cluster.go
  model/kops_metadata.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#476 Add multitenant database update API endpoint
  cmd/cloud/databases.go
  internal/api/cluster.go
  internal/api/common_test.go
  internal/api/databases.go
  internal/api/databases_test.go
  internal/api/lock.go
  internal/store/multitenant_database.go
  internal/tools/aws/constants.go
  model/client.go
  model/multitenant_database.go
  model/multitenant_database_request.go
Labels: 2: Dev Review, kind/feature, release-note

#475 Update kops to 1.20, k8s to 1.20.8 and terraform to 0.12.31
  Makefile
Labels: 4: Reviews Complete, kind/feature, release-note

#477 Set `binary_parameters=yes` for PGBouncer databases
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/helpers_sql.go
Labels: 4: Reviews Complete, kind/bug, release-note

#478 MM-37097-migration-fix-installation-bifrost
  internal/tools/aws/helpers.go
Labels: 4: Reviews Complete, release-note

#473 Cleanup clusters API handlers to align with installations API
  internal/api/cluster.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#480 [MM-36314] Add support for Stackrox and remove local utility Helm values dependency.
  README.md
  build/Dockerfile
  cmd/cloud/cluster.go
  cmd/cloud/server.go
  helm-charts/fluent-bit_values.yaml
  helm-charts/nginx_internal_values.yaml
  helm-charts/nginx_values.yaml
  helm-charts/pgbouncer_values.yaml
  helm-charts/prometheus_operator_values.yaml
  helm-charts/stackrox_values.yaml
  helm-charts/teleport_values.yaml
  helm-charts/thanos_values.yaml
  internal/api/request_test.go
  internal/provisioner/stackrox.go
  internal/provisioner/utility_group.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#481 Add DB migration e2e test
  Makefile
  README.md
  e2e/pkg/db_migration.go
  e2e/pkg/dns.go
  e2e/pkg/export.go
  e2e/pkg/installation.go
  e2e/pkg/installation_builder.go
  e2e/pkg/k8s.go
  e2e/pkg/wait.go
  e2e/tests/dbmigration/db_migration_test.go
  e2e/tests/dbmigration/steps.go
  e2e/tests/dbmigration/suite.go
  e2e/workflow/db_migration.go
  e2e/workflow/engine.go
  e2e/workflow/installation.go
  go.mod
  go.sum
Labels: 4: Reviews Complete, kind/feature, release-note

#479 Add kubecost helm chart
  cmd/cloud/cluster.go
  cmd/cloud/server.go
  helm-charts/kubecost_values.yaml
  internal/api/request_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kubecost.go
  internal/provisioner/utility_group.go
  model/cluster.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#483 Update to latest Calico CNI
  internal/provisioner/kops_provisioner_cluster.go
  manifests/calico-policy-only.yaml
Labels: 2: Infra Review, kind/bug, release-note

#485 MM-33987 - Skip cluster deletion if it does not exist
  cmd/cloud/cluster.go
  cmd/cloud/server.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kubecost.go
  internal/tools/kops/cluster.go
  model/cluster.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, kind/bug, release-note

#487 Keep two versions of calico used based on cni used in cluster
  internal/provisioner/kops_provisioner_cluster.go
  manifests/calico-cni.yaml
  manifests/calico-network-policy-only.yaml
Labels: kind/bug, release-note
