Repository mattermost/mattermost-cloud, pull requests merged in 2021-08, with the labels that each got.

#484 Mm 37196 migrating hibernated installations
  internal/api/cluster_installation.go
  internal/api/context.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/store/cluster_installation.go
  internal/store/cluster_installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
  internal/tools/aws/route53_test.go
  model/installation_states.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#491 MM-37571-locking-installations for all type of installations
  internal/api/cluster_installation.go
  internal/api/cluster_installation_test.go
  internal/store/cluster_installation_test.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#490 Add installation deployment report command
  cmd/cloud/backup.go
  cmd/cloud/installation.go
  cmd/cloud/installation_operation_db_migration.go
  cmd/cloud/installation_operation_restoration.go
  internal/store/cluster.go
  internal/store/cluster_installation.go
  internal/store/group.go
  internal/store/installation.go
  internal/store/installation_backup.go
  internal/store/installation_db_migration.go
  internal/store/installation_db_restoration_operation.go
  internal/store/lock.go
  internal/store/multitenant_database.go
  internal/store/util.go
  internal/store/webhook.go
  internal/supervisor/db_migration.go
  model/installation.go
  model/installation_database.go
  model/installation_database_test.go
  model/time.go
Labels: 2: Dev Review, kind/feature, release-note

#488 Add option to retry cluster creation from command line
  cmd/cloud/cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#493 Fix formatting after enforcing stricter rules
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
Labels: kind/bug, kind/cleanup, release-note-none

#489 Add a new tool for testing provisioner installations like a real user
  cmd/tools/testwick/.gitignore
  cmd/tools/testwick/Makefile
  cmd/tools/testwick/go.mod
  cmd/tools/testwick/go.sum
  cmd/tools/testwick/main.go
  cmd/tools/testwick/runner.go
  cmd/tools/testwick/testwicker.go
Labels: 2: Dev Review, kind/feature, release-note

#494 MM-32924 - Configure Node and AZ anti-affinity for MM pods
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
Labels: 4: Reviews Complete, kind/feature, release-note

#495 Cancel Imports made against deleted Installations
  internal/supervisor/import.go
Labels: 2: Dev Review, release-note

#496 Add unit tests for testwick
  .circleci/config.yml
  cmd/tools/testwick/Makefile
  cmd/tools/testwick/go.mod
  cmd/tools/testwick/go.sum
  cmd/tools/testwick/main.go
  cmd/tools/testwick/wicker/mocks/testwicker.go
  cmd/tools/testwick/wicker/runner.go
  cmd/tools/testwick/wicker/testwicker.go
  cmd/tools/testwick/wicker/testwicker_test.go
Labels: kind/feature, release-note-none

#492 MM-37622-fix-clusterid-starting-with-digit
  internal/provisioner/kops_provisioner_cluster.go
  internal/store/cluster.go
  model/id.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#497 Standardize multitenant database IDs
  internal/api/databases_test.go
  internal/api/installation_db_migration_test.go
  internal/store/migrations.go
  internal/store/multitenant_database.go
  internal/store/multitenant_database_test.go
  internal/store/store.go
  internal/supervisor/db_migration_test.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_multitenant_test.go
  model/multitenant_database.go
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#499 Check v1beta1 reconciling resources with ObservedGeneration
  go.mod
  go.sum
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/installation.go
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermost_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermostrestoredb_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
  manifests/operator-manifests/mattermost/role_binding.yaml
Labels: 2: Dev Review, kind/feature, release-note

#498 Fix AWAT import completion synchronization bug
  internal/supervisor/import.go
  internal/supervisor/import_test.go
  internal/supervisor/installation_test.go
  model/installation_states.go
Labels: 2: Dev Review, release-note

#482 Feat/mm 37302
  go.mod
  go.sum
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/iam.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/route53.go
  internal/mocks/aws-sdk/s3.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/provisioner/kops_provisioner_installation_sli.go
  k8s/client.go
  k8s/custom_resources.go
  k8s/custom_resources_test.go
  k8s/manifest.go
  k8s/namespaces.go
  manifests/sloth/crd_sloth.slok.dev_prometheusservicelevels.yaml
  manifests/sloth/sloth.yaml
  manifests/sloth/sloth_pod_monitor.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#500 Convert installation DNS to lowercase
  internal/api/installation_test.go
  model/installation_request.go
  model/installation_request_test.go
Labels: 2: Dev Review, kind/bug, release-note

#501 Add extra fields in table for cluster list
  cmd/cloud/cluster.go
Labels: kind/feature, release-note

#502 Fix wrong label on SLI Prometheus queries
  internal/provisioner/kops_provisioner_installation_sli.go
Labels: kind/bug, release-note

#505 Improve secret manager secret cleanup
  internal/tools/aws/constants.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/secrets_manager.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#512 Small utility logic improvements
  cmd/cloud/server.go
  internal/api/cluster.go
  internal/provisioner/helm_utils.go
  model/cluster_utility.go
Labels: 4: Reviews Complete, kind/cleanup, release-note-none

#514 BugFix: Re-provision failure of sloth
  k8s/custom_resources.go
Labels: kind/bug, release-note
