Repository mattermost/mattermost-cloud, pull requests merged in 2021-06, with the labels that each got.

#461 Add DB migration rollback mechanism and cleanup for restorations and migrations
  internal/store/installation_db_migration.go
  internal/store/installation_db_migration_test.go
  internal/store/installation_db_restoration_operation.go
  internal/store/installation_db_restoration_operation_test.go
  internal/supervisor/db_migration.go
  internal/supervisor/db_migration_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_db_restoration.go
  internal/supervisor/installation_db_restoration_test.go
  internal/supervisor/installation_test.go
  model/installation_db_migration_operation.go
  model/installation_db_migration_operation_test.go
  model/installation_db_restoration_operation.go
  model/installation_states.go
Labels: 4: Reviews Complete, kind/feature, release-note

#463 Add DatabseBackupType to Installation backup
  internal/api/installation_backup_test.go
  internal/common/installation_backup.go
  internal/store/installation_backup.go
  internal/store/installation_backup_test.go
  internal/store/migrations.go
  internal/supervisor/db_migration_test.go
  model/installation_backup.go
Labels: 4: Reviews Complete, kind/feature, release-note

#467 Support importing Mattermost workspaces from the AWAT
  go.mod
  go.sum
  internal/supervisor/import.go
Labels: 2: Dev Review, release-note-none

#465 MM-35892 - Add API for DB migrations
  internal/api/context.go
  internal/api/helpers.go
  internal/api/installation.go
  internal/api/installation_db_migration.go
  internal/api/installation_db_migration_test.go
  internal/api/lock.go
  model/client.go
Labels: 4: Reviews Complete, kind/feature, release-note

#470 [MM-36420] Add flags and logic to control mysql and minio operator deployments in cloud clusters.
  cmd/cloud/installation.go
  cmd/cloud/server.go
  internal/api/group_test.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, release-note

#471 Add log message when Installation annotations do not match any cluster
  internal/supervisor/installation.go
Labels: 4: Reviews Complete, kind/feature, release-note
