Repository mattermost/mattermost-cloud, pull requests merged in 2021-11, with the labels that each got.

#567 [MM-39516] Update provisioner to use new rotator release with drain speed control
  cmd/cloud/cluster.go
  go.mod
  go.sum
  internal/provisioner/kops_provisioner_cluster.go
  model/cluster_request.go
  model/kops_metadata.go
Labels: 4: Reviews Complete, release-note

#566 Bump Operator to 1.16
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/crds/mm_mattermost_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
  manifests/operator-manifests/mattermost/service_account.yaml
  manifests/operator-manifests/minio/minio-operator.yaml
  manifests/operator-manifests/mysql/mysql-operator.yaml
Labels: kind/feature, release-note

#568 Update CRDs instead of patching
  k8s/custom_resources.go
Labels: 4: Reviews Complete, kind/bug, release-note

#569 Change k8s resource calculations
  internal/provisioner/kops_provisioner_cluster.go
  k8s/resources.go
Labels: 2: Infra Review, kind/bug, release-note

#570 Make AWS tests compatible with gomock 1.6.0
  go.mod
  go.sum
  internal/tools/aws/client_test.go
  internal/tools/aws/database_migration_test.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/database_test.go
  internal/tools/aws/ec2_test.go
  internal/tools/aws/rds_test.go
Labels: 4: Reviews Complete, release-note, kind/chore

#571 Adjust DB migration to Mattermost v6
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/supervisor/db_migration.go
Labels: 4: Reviews Complete, kind/bug, release-note

#572 Cleanup database migration backups
  internal/store/migrations.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#573 Bump k8s-spot-termination-handler to fix security vulnerabilities
  manifests/k8s-spot-termination-handler/k8s-spot-termination-handler.yaml
Labels: release-note, kind/chore

#562 Only reprovision utilities when forced or version is explicitly specified
  cmd/cloud/cluster.go
  internal/api/cluster.go
  internal/provisioner/fluentbit.go
  internal/provisioner/fluentbit_test.go
  internal/provisioner/kubecost.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/node_problem_detector.go
  internal/provisioner/node_problem_detector_test.go
  internal/provisioner/pgbouncer.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/stackrox.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  model/cluster_request.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#575 Remove v1alpha1 CR support
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/store/installation_test.go
  internal/supervisor/installation_test.go
  model/installation.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#577 pgbouncer config pool sizes update as per fine-tuning
  cmd/cloud/server.go
  internal/provisioner/pgbouncer.go
  manifests/pgbouncer-manifests/pgbouncer-configmap.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note
