Repository mattermost/mattermost-cloud, pull requests merged in 2021-02, with the labels that each got.

#410 Upgrade to kops 1.18.3, terraform 0.12.29 and kubectl version 1.18.15
  .gitignore
  Makefile
  README.md
  internal/tools/terraform/plan.go
Labels: 4: Reviews Complete, release-note

#409 Improved server startup check
  cmd/cloud/server.go
  internal/tools/helm/commands.go
  internal/tools/terraform/plan.go
Labels: 4: Reviews Complete, kind/feature, release-note

#412 Allow installation updates on OwnerID
  cmd/cloud/installation.go
  model/installation.go
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#411 Add hibernated domain redirection to nginx ingress
  cmd/cloud/server.go
  helm-charts/nginx_values.yaml
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster_installation_beta.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/route53.go
Labels: 2: Infra Review, kind/feature, release-note

#413 Improve hibernation logic
  cmd/cloud/dashboard.go
  internal/store/group.go
  internal/store/group_test.go
  internal/supervisor/group.go
  model/group_status.go
Labels: 4: Reviews Complete, kind/feature, release-note

#414 Allow hibernating installations to be deleted
  internal/supervisor/installation.go
  model/installation_states.go
Labels: 2: Infra Review, kind/feature, release-note

#416 Releasing operator v1.13.0 in mattermost cloud
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#419 Optimize route53 record lookup
  go.mod
  go.sum
  internal/supervisor/installation.go
  internal/tools/aws/route53.go
Labels: 4: Reviews Complete, kind/feature, release-note

#418 [MM-33040] Reduce the limit for workspace from 3 to 2 chars
  model/installation_request.go
Labels: 4: Reviews Complete, release-note

#420 Enhance AWS client with a resource cache
  cmd/cloud/server.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/fluentbit.go
  internal/provisioner/fluentbit_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/helpers.go
  internal/tools/aws/route53.go
  internal/tools/aws/route53_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#415 Migrating to official Fluent-bit helm chart and parsing audit logs from k8s masters
  helm-charts/fluent-bit_values.yaml
  internal/api/request_test.go
  internal/provisioner/fluentbit.go
  internal/provisioner/fluentbit_test.go
  model/cluster_utility.go
Labels: 4: Reviews Complete, kind/feature, release-note

#422 Removing Helm stable chart - add fluent bit official chart
  internal/provisioner/utility_group.go
Labels: kind/cleanup, release-note

#421 MM-32795: Avoid upgrade and resize removal of role policy attachment
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
Labels: 4: Reviews Complete, kind/bug, release-note
