Repository mattermost/mattermost-cloud, pull requests merged in 2021-12, with the labels that each got.

#574 Add Provisioner Events model and store
  internal/store/events.go
  internal/store/events_subscription.go
  internal/store/events_subscription_test.go
  internal/store/events_test.go
  internal/store/lock.go
  internal/store/migrations.go
  model/client.go
  model/events.go
  model/events_state_change.go
  model/events_state_change_test.go
  model/events_subscription.go
  model/events_subscription_request.go
  model/events_subscription_request_test.go
  model/events_subscription_test.go
  model/events_test.go
  model/general.go
  model/webhook.go
  model/webhook_test.go
Labels: 2: Dev Review, kind/feature, release-note

#579 Bump kubecost to 1.88.1
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note, kind/chore

#578 Implement event Producer and Deliverer
  internal/events/delivery.go
  internal/events/delivery_test.go
  internal/events/producer.go
  internal/events/producer_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#581 Add Subscriptions and Events API and CLI
  cmd/cloud/events.go
  cmd/cloud/events_subscription.go
  cmd/cloud/main.go
  cmd/cloud/server.go
  internal/api/api.go
  internal/api/context.go
  internal/api/events.go
  internal/api/events_subscription.go
  internal/api/events_subscription_test.go
  internal/api/webhook.go
  model/client.go
Labels: 4: Reviews Complete, kind/feature, release-note

#580 [MM-40438] Add support for new Teleport Kube Agent utility
  internal/api/request_test.go
  internal/provisioner/teleport.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#582 Bump bifrost to v1.0.3
  manifests/bifrost/bifrost.yaml
Labels: release-note, kind/chore

#584 Bump alpine to 3.14 and golang to 1.17.4
  .circleci/config.yml
  Makefile
  build/Dockerfile
Labels: release-note, kind/chore

#585 Enable Provisioner events for Installation, Cluster and Cluster Installation
  cmd/cloud/server.go
  internal/api/cluster.go
  internal/api/cluster_installation_test.go
  internal/api/cluster_test.go
  internal/api/events_test.go
  internal/api/group_test.go
  internal/api/installation.go
  internal/api/installation_backup_test.go
  internal/api/installation_db_migration.go
  internal/api/installation_db_migration_test.go
  internal/api/installation_db_restoration_operation.go
  internal/api/installation_db_restoration_operation_test.go
  internal/api/installation_test.go
  internal/common/installation_restoration.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/cluster_test.go
  internal/supervisor/db_migration.go
  internal/supervisor/db_migration_test.go
  internal/supervisor/group.go
  internal/supervisor/group_test.go
  internal/supervisor/import.go
  internal/supervisor/import_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_db_restoration.go
  internal/supervisor/installation_db_restoration_test.go
  internal/supervisor/installation_test.go
  internal/testutil/events.go
Labels: 4: Reviews Complete, kind/feature, release-note

#587 [MM-40757] Release new Operator v1.17.0 in Cloud provisioner
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/crds/mm_clusterinstallation_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermost_crd.yaml
  manifests/operator-manifests/mattermost/crds/mm_mattermostrestoredb_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
  manifests/operator-manifests/mattermost/role_binding.yaml
  manifests/operator-manifests/mattermost/service.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#588 Add the missing apiVersion in the clusterrole
  manifests/operator-manifests/mattermost/role.yaml
Labels: kind/bug, release-note
