Repository mattermost/mattermost-cloud, pull requests merged in 2022-06, with the labels that each got.

#656 Deploy RTCD helm chart with provisioner
  cmd/cloud/cluster.go
  helm-charts/rtcd_values.yaml
  internal/api/request_test.go
  internal/provisioner/rtcd.go
  internal/provisioner/utility_group.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Infra Review, kind/feature, release-note

#659 Add mattermost helm repo
  internal/provisioner/utility_group.go
Labels: release-note-none

#660 Add an extra policy so the node have velero permissions
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/constants.go
Labels: kind/feature, release-note

#661 Handle Cloudflare record creation idempotently
  internal/tools/cloudflare/client.go
  internal/tools/cloudflare/dns.go
  internal/tools/cloudflare/dns_test.go
  internal/tools/cloudflare/mocks.go
Labels: kind/bug, release-note

#663 fix bug with rtcd helm chart prefix
  internal/provisioner/rtcd.go
Labels: kind/bug, release-note

#662 [CLD-2448] Revert calls node group skip AMI rotation
  internal/provisioner/kops_utils.go
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#664 [fix] Detach velero node policy on cluster deletion
  internal/provisioner/kops_provisioner_cluster.go
Labels: 2: Dev Review, kind/bug, release-note

#665 Add ability to add domains to existing Installations and switch primary domain
  cmd/cloud/installation.go
  cmd/cloud/installation_dns.go
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_dns.go
  internal/api/installation_dns_test.go
  internal/store/installation_dns.go
  internal/store/installation_dns_test.go
  internal/supervisor/installation.go
  internal/tools/cloudflare/dns.go
  model/client.go
Labels: 4: Reviews Complete, kind/feature, release-note

#669 Add ingress annotation reflecting the Installation hibernation state
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: kind/feature, release-note

#670 [CLD-2533] Increase max installations per db to 2500 to handle scale
  internal/tools/aws/constants.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#671 Change annotation reflecting the Installation hibernation state to label
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: kind/feature, release-note

#672 [CLD-2557] Update provisioner cluster upgrade defaults for better drain stability
  cmd/cloud/cluster.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#673 Add option to force restart Installations in the group
  cmd/cloud/group.go
  internal/api/group_test.go
  model/group_request.go
  model/group_request_test.go
Labels: release-note
