Repository mattermost/mattermost-cloud, pull requests merged in 2022-07, with the labels that each got.

#675 Add flags to configure max Installations per DB cluster
  cmd/cloud/server.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/helpers.go
  internal/tools/utils/utils.go
Labels: release-note

#667 Optimize DNS search path
  cmd/cloud/server.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#680 Fix cloudprober helm handler
  internal/provisioner/utility_group.go
Labels: kind/bug, release-note

#677 Increase pgbouncer max client connections
  cmd/cloud/server.go
  internal/provisioner/pgbouncer.go
  manifests/pgbouncer-manifests/pgbouncer-configmap.yaml
  model/multitenant_database.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note, kind/refactor

#682 Use cluster resource cache for final scheduling action
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation.go
  k8s/resources.go
Labels: 4: Reviews Complete, kind/feature, release-note

#685 [CLD-3774] Allow mattermost port to be accessed by prometheus in network policy
  manifests/network-policies/mm-installation-netpol.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#684 Accept 'ready' for Cluster Installation; Update Operator to 1.19.0-rc.0
  go.mod
  go.sum
  internal/provisioner/kops_provisioner_cluster_installation.go
  manifests/operator-manifests/mattermost/operator.yaml
Labels: release-note

#690 Support custom Installation sizes in Provisioner
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/supervisor/installation.go
  model/group_dto_test.go
  model/installation_request.go
  model/installation_request_test.go
  model/mattermost_size.go
  model/mattermost_size_test.go
Labels: 4: Reviews Complete, release-note

#688 Bump sloth to v0.10.0
  manifests/sloth/sloth.yaml
Labels: 2: Infra Review, release-note, kind/chore

#692 Bump Operator to 1.19.0-rc.1
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/operator.yaml
Labels: release-note

#691 Add cluster resource threshold scheduling overrides
  cmd/cloud/server.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note
