Repository mattermost/mattermost-cloud, pull requests merged in 2022-09, with the labels that each got.

#711 CLD 3784 Bump Velero version
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#708 Upgrade kops to 1.22
  .circleci/config.yml
  Makefile
  README.md
  build/Dockerfile
  cmd/cloud/table_printer.go
  internal/api/cluster.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/env.go
Labels: release-note, kind/chore

#712 Improve pgbouncer DNS performance
  internal/tools/aws/helpers_sql.go
Labels: 4: Reviews Complete, release-note

#713 Add more error logging for mmctl failures
  cmd/cloud/dashboard.go
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 2: Dev Review, kind/cleanup, release-note

#714 Add temporary exec pod logging
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 2: Dev Review, release-note-none

#710 Fix sloth check on provision phase
  internal/provisioner/kops_provisioner_cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#715 Add cluster-installation `ready` state
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/cluster_installation_states.go
Labels: 4: Reviews Complete, kind/feature, release-note

#716 Increase installation report command output
  cmd/cloud/installation.go
Labels: 4: Reviews Complete, kind/feature, release-note

#717 Revert "Upgrade kops to 1.22 (#708)"
  .circleci/config.yml
  Makefile
  README.md
  build/Dockerfile
  cmd/cloud/table_printer.go
  internal/api/cluster.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/env.go
Labels: 2: Infra Review, release-note-none, kind/chore

#719 Revert "Revert "Upgrade kops to 1.22 (#708)""
  .circleci/config.yml
  Makefile
  README.md
  build/Dockerfile
  cmd/cloud/table_printer.go
  internal/api/cluster.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/env.go
Labels: release-note-none, kind/chore

#721 Revert "Revert "Revert "Upgrade kops to 1.22 (#708)"""
  .circleci/config.yml
  Makefile
  README.md
  build/Dockerfile
  cmd/cloud/table_printer.go
  internal/api/cluster.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/env.go
Labels: 2: Infra Review, release-note-none, kind/chore

#723 Add multitenant database report command
  cmd/cloud/databases.go
  model/installation.go
  model/multitenant_database.go
  model/time.go
Labels: 2: Infra Review, kind/feature, release-note

#725 Cleanup installation supervisor unit tests
  internal/supervisor/installation_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note-none

#727 Update client to use newer database endpoints
  model/client.go
Labels: 4: Reviews Complete, kind/cleanup, release-note
