Repository mattermost/mattermost-cloud, pull requests merged in 2022-04, with the labels that each got.

#628 Upgrade default versions for Thanos, Prometheus and Nginx
  README.md
  internal/api/cluster_test.go
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note, kind/chore

#624 Increase timeout k8s-spot-termination-handler
  internal/provisioner/kops_provisioner_cluster.go
Labels: kind/bug, release-note

#629 Bump terraform version to v0.14.11
  Makefile
  README.md
Labels: release-note, kind/chore

#631 Use Calico as default
  internal/api/request_test.go
  model/cluster_request.go
Labels: release-note

#633 Improve e2e test edge cases, fix populate sample data command
  e2e/pkg/eventstest/handler.go
  e2e/pkg/webhook_handler.go
  e2e/tests/cluster/cluster_test.go
  e2e/tests/cluster/suite.go
  e2e/workflow/installation.go
Labels: 4: Reviews Complete, release-note

#632 Add cluster resource cache
  internal/api/common_test.go
  internal/api/context.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#636 [MM-43296] Upgrade Promtail to v2.5.0 via 4.2.0 Helm chart version
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#635 [MM-43347] Add custom nginx template and nginx namespace handling
  internal/provisioner/kops_provisioner_cluster.go
  manifests/nginx/nginx_template.yaml
Labels: 2: Dev Review, 2: Infra Review, release-note

#637 Fetch AMI from existing clusters in e2e
  e2e/pkg/cluster.go
  e2e/tests/cluster/suite.go
Labels: 4: Reviews Complete, kind/feature, release-note

#617 Update DNS logic to use both Route53 and Cloudflare
  blah.txt
  cmd/cloud/server.go
  go.mod
  go.sum
  internal/mocks/aws-tools/client.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
  internal/tools/cloudflare/client.go
  internal/tools/cloudflare/dns.go
  internal/tools/cloudflare/dns_test.go
  internal/tools/cloudflare/mocks.go
Labels: 4: Reviews Complete, kind/feature, release-note
