Repository mattermost/mattermost-cloud, pull requests merged in 2022-08, with the labels that each got.

#681 Remove Blackbox related logic from hibernation flow
  internal/mocks/aws-tools/client.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
Labels: release-note

#693 Add option to disable DB check init containers
  cmd/cloud/server.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/database_test.go
  internal/tools/aws/secret.go
  internal/tools/aws/secret_test.go
  internal/tools/aws/session_test.go
  internal/tools/utils/utils.go
Labels: 4: Reviews Complete, release-note

#696 [CLD-3770] Upgrade Promtail to 6.2.2
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#697 Add option to enable/disable Route53 DNS records creation
  cmd/cloud/server.go
  internal/mocks/aws-tools/client.go
  internal/supervisor/dns.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
Labels: 4: Reviews Complete, release-note

#689 Bump kube-spot-termination-notice-handler to v1.21.2
  manifests/k8s-spot-termination-handler/k8s-spot-termination-handler.yaml
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#699 [CLD-3928] Revert Thanos back on 0.26.0 version to fix introduced decoupling bugs
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#687 Bump kubecost to v1.95.0
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#698 Fix max nodes cluster value updates
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_utils.go
  internal/provisioner/kops_utils_test.go
  internal/supervisor/cluster.go
  internal/supervisor/dns.go
  internal/tools/kops/instance_groups.go
  model/kops_metadata.go
  model/kops_metadata_test.go
Labels: 2: Dev Review, kind/bug, release-note

#694 Upgrade nginx-internal to v4.2.0
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Infra Review, release-note, kind/chore

#700 Add installation deletion queuing
  cmd/cloud/installation.go
  cmd/cloud/server.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_deletion.go
  internal/supervisor/installation_deletion_test.go
  internal/supervisor/installation_test.go
  model/client.go
  model/installation.go
  model/installation_states.go
  model/installation_states_test.go
  model/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#701 Add flag to disable DNS updates on Installation update
  cmd/cloud/server.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: release-note

#702 Installation deletion pending review
  cmd/cloud/dashboard.go
  cmd/cloud/server.go
  internal/store/group.go
  internal/store/group_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/supervisor/installation_deletion.go
  model/group_status.go
  model/installation_status.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#703 Add installation deletion limit
  cmd/cloud/server.go
  internal/supervisor/installation_deletion.go
  internal/supervisor/installation_deletion_test.go
Labels: 2: Dev Review, kind/feature, release-note

#707 Bump terraform to v0.15.5
  Makefile
  README.md
Labels: release-note, kind/chore

#706 Refactor utilities to not depend on Kops
  internal/provisioner/cloudprober.go
  internal/provisioner/fluentbit.go
  internal/provisioner/fluentbit_test.go
  internal/provisioner/helm_utils.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kubecost.go
  internal/provisioner/metrics_server.go
  internal/provisioner/metrics_server_test.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/node_problem_detector.go
  internal/provisioner/node_problem_detector_test.go
  internal/provisioner/pgbouncer.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/promtail.go
  internal/provisioner/rtcd.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  internal/provisioner/velero.go
Labels: 4: Reviews Complete, release-note

#709 Add query time stats to the dashboard command
  cmd/cloud/dashboard.go
Labels: 4: Reviews Complete, kind/feature, release-note
