Repository mattermost/mattermost-cloud, pull requests merged in 2022-11, with the labels that each got.

#758 Increase default evict grace period.
  cmd/cloud/cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#760 Set default_text_search_config to pg_catalog.english
  internal/tools/aws/database_multitenant_pgbouncer.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#756 [MM-47887] Tag RDS resources with the ClusterID they belong to
  internal/tools/aws/constants.go
  internal/tools/aws/database.go
  internal/tools/aws/rds.go
  internal/tools/aws/rds_test.go
  internal/tools/aws/tags.go
  internal/tools/aws/tags_test.go
Labels: 4: Reviews Complete, release-note

#759 feat: allow disabling supervisors or running cloud in api only mode
  cmd/cloud/server.go
Labels: 4: Reviews Complete, release-note-none

#763 Add recent events to installation report cmd output
  cmd/cloud/installation.go
Labels: 4: Reviews Complete, kind/feature, release-note

#765 test: fixed non deterministic result check
  internal/tools/aws/tags.go
  internal/tools/aws/tags_test.go
Labels: 4: Reviews Complete, kind/bug, release-note-none

#764 [MM-46231] Migrate to AWS SDK v2 [acm]
  go.mod
  go.sum
  internal/mocks/aws-sdk/acm.go
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/pgbouncer.go
  internal/supervisor/installation_test.go
  internal/tools/aws/acm.go
  internal/tools/aws/acm_test.go
  internal/tools/aws/acm_types.go
  internal/tools/aws/client.go
  internal/tools/aws/config.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/helpers.go
  internal/tools/aws/secrets_manager.go
  model/aws_types.go
  model/installation_database.go
  model/password.go
Labels: 4: Reviews Complete, release-note

#767 [CLD-4033] Update Cloudprober to latest version
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#768 [MM-46277] Properly (un)tag VPCs when releasing clusters from VPCs
  Makefile
  go.sum
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/cluster_management_test.go
Labels: 4: Reviews Complete, release-note

#772 [CLD-4568] Create installation SLIs based on ring preferences
  cmd/cloud/server.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/kops_provisioner.go
  internal/supervisor/installation.go
Labels: 2: Dev Review, kind/feature, release-note

#771 refinement of flag parsing (cloud server)
  .gitignore
  Makefile
  cmd/cloud/installation.go
  cmd/cloud/main.go
  cmd/cloud/schema.go
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
Labels: release-note-none

#769 added support to set etcd manager envs
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
Labels: 4: Reviews Complete, release-note
