Repository mattermost/mattermost-cloud, pull requests merged in 2022-05, with the labels that each got.

#634 Support multiple domains for Installation
  cmd/cloud/installation.go
  cmd/cloud/table_printer_test.go
  internal/api/cluster_installation_test.go
  internal/api/cluster_test.go
  internal/api/context.go
  internal/api/db_multitenant_database_test.go
  internal/api/installation.go
  internal/api/installation_db_migration_test.go
  internal/api/installation_test.go
  internal/common/installation_db_migration_test.go
  internal/events/producer.go
  internal/events/producer_test.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/annotation.go
  internal/store/annotation_test.go
  internal/store/cluster_installation_test.go
  internal/store/db_multitenant_database_test.go
  internal/store/group_test.go
  internal/store/installation.go
  internal/store/installation_backup_test.go
  internal/store/installation_dns.go
  internal/store/installation_dns_test.go
  internal/store/installation_dto.go
  internal/store/installation_dto_test.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/store/util.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/db_migration_test.go
  internal/supervisor/group_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_db_restoration_test.go
  internal/supervisor/installation_test.go
  internal/testutil/backup.go
  internal/testutil/dns.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
  internal/tools/cloudflare/client.go
  internal/tools/cloudflare/dns.go
  internal/tools/cloudflare/dns_test.go
  internal/tools/cloudflare/mocks.go
  model/installation.go
  model/installation_dns.go
  model/installation_dns_test.go
  model/installation_dto.go
  model/installation_dto_test.go
  model/installation_request.go
  model/installation_request_test.go
  model/installation_test.go
Labels: kind/feature, release-note

#638 Allow events to appear in switched order
  e2e/pkg/eventstest/handler.go
Labels: 4: Reviews Complete, kind/bug, release-note

#641 Revert custom NGINX template as not needed
  internal/provisioner/kops_provisioner_cluster.go
  manifests/nginx/nginx_template.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/bug, kind/cleanup, release-note

#645 [MM-43153] Add support for metrics server utility
  cmd/cloud/cluster.go
  helm-charts/metrics_server_values.yaml
  internal/api/request_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/metrics_server.go
  internal/provisioner/metrics_server_test.go
  internal/provisioner/utility_group.go
  manifests/metric-server/metric-server.yaml
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#646 [MM-44469] Set default Prometheus version to latest stable
  internal/api/cluster_test.go
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#643 Add max pods per worker node configuration option
  cmd/cloud/cluster.go
  internal/api/cluster.go
  internal/api/request_test.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/kops/cluster.go
  internal/tools/kops/instance_groups.go
  model/cluster_request.go
  model/cluster_request_test.go
  model/kops_metadata.go
Labels: 2: Dev Review, kind/feature, release-note

#644 Group selection based on annotations
  cmd/cloud/group.go
  cmd/cloud/installation.go
  cmd/tools/cloudburst/cloudburst.go
  internal/api/context.go
  internal/api/group.go
  internal/api/group_test.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/api/lock.go
  internal/store/annotation.go
  internal/store/annotation_test.go
  internal/store/cluster_installation_test.go
  internal/store/group.go
  internal/store/group_dto.go
  internal/store/group_dto_test.go
  internal/store/group_test.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/supervisor/group_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/annotation.go
  model/client.go
  model/group.go
  model/group_dto.go
  model/group_dto_test.go
  model/group_request.go
  model/installation_request.go
Labels: 4: Reviews Complete, kind/feature, release-note

#648 [CLD-1501] Upgrade Fluentbit to latest stable version
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#647 Skip AMI update for calls instance group
  internal/provisioner/kops_utils.go
Labels: 4: Reviews Complete, kind/feature, release-note

#640 Add velero in our kops cluster
  cmd/cloud/cluster.go
  helm-charts/velero_values.yaml
  internal/api/request_test.go
  internal/provisioner/utility_group.go
  internal/provisioner/velero.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#655 Fix helm repos list for utilities
  internal/provisioner/utility_group.go
Labels: kind/bug, release-note

#657 Add endpoints to modify Group annotations
  cmd/cloud/group.go
  cmd/cloud/group_annotation.go
  internal/api/context.go
  internal/api/group.go
  internal/api/group_test.go
  internal/api/installation.go
  internal/store/annotation.go
  internal/store/annotation_test.go
  internal/store/group_dto_test.go
  internal/store/group_test.go
  internal/store/migrations.go
  model/client.go
Labels: 4: Reviews Complete, kind/feature, release-note
