Repository mattermost/mattermost-cloud, pull requests merged in 2022-03, with the labels that each got.

#615 Increase S3 import chunk size
  internal/tools/aws/s3.go
Labels: 2: Dev Review, kind/bug, release-note

#616 Use HistogramVec to collect metrics
  internal/metrics/metrics.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/installation.go
Labels: 2: Dev Review, kind/feature, release-note

#614 Hide installation env vars in CLI output
  cmd/cloud/installation.go
Labels: 4: Reviews Complete, kind/feature, release-note

#618 Add `PriorityEnv` support to Installations
  cmd/cloud/installation.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/store/migrations.go
  model/env.go
  model/installation.go
  model/installation_request.go
  model/installation_request_test.go
  model/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#621 [MM-42455] Fix a bug where teleport applies wrong version during reprovisioning
  internal/provisioner/teleport.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#622 Add delete multi-tenant database endpoint
  cmd/cloud/databases.go
  internal/api/context.go
  internal/api/db_multitenant_database.go
  internal/api/db_multitenant_database_test.go
  internal/store/db_multitenant_database.go
  internal/store/db_multitenant_database_test.go
  internal/tools/aws/rds.go
  model/client.go
Labels: 4: Reviews Complete, kind/feature, release-note

#625 Use new CR ingress config
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 4: Reviews Complete, release-note, kind/chore

#626 Use new ingress spec for hibernation
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 4: Reviews Complete, kind/bug, release-note-none

#627 Bump dependencies and other small improvements
  .circleci/config.yml
  blah.txt
  cmd/cloud/dashboard.go
  go.mod
  go.sum
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-sdk/rds.go
  internal/supervisor/import.go
Labels: 2: Dev Review, release-note, kind/chore
