Repository mattermost/mattermost-cloud, pull requests merged in 2022-10, with the labels that each got.

#729 Add external database type support
  cmd/cloud/installation.go
  internal/api/context.go
  internal/api/db_multitenant_database_test.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/mocks/aws-tools/client.go
  internal/mocks/model/installation_database.go
  internal/store/installation.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/database_external.go
  internal/tools/aws/helpers.go
  internal/tools/utils/utils.go
  model/external_database.go
  model/external_database_test.go
  model/installation.go
  model/installation_database.go
  model/installation_request.go
  model/installation_request_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#730 Temporary disable calico-node daemonset check
  internal/provisioner/kops_provisioner_cluster.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#731 [CLD-4269] Migrate calico cni only APIs from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1
  manifests/calico-network-policy-only.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#732 [CLD-4270 ] Update out of date CRDs for Calico policy only manifests
  manifests/calico-network-policy-only.yaml
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#733 Add pod phase status field in mmctl logs
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: 2: Dev Review, kind/cleanup, release-note-none

#734 Optimize fetching InstallationDNS
  internal/store/installation_dns.go
  internal/store/installation_dto.go
  internal/store/migrations.go
Labels: 4: Reviews Complete, release-note

#735 [CLD-4284] Fix missing kubeconfig path for node problem detector
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/node_problem_detector.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#741 Sort DNS records in test for deterministic outcome
  internal/api/installation_dns.go
  internal/api/installation_dns_test.go
Labels: release-note-none

#738 Refactor calico to be handled by Kops
  internal/provisioner/kops_provisioner_cluster.go
  manifests/calico-cni.yaml
Labels: release-note, kind/refactor

#737 Kops upgrade to 1.23 and terraform bump to v1.0.7
  .circleci/config.yml
  Makefile
  README.md
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#740 Change instance metadata httpTokens default behavior.
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_utils.go
Labels: release-note, kind/chore

#695 Upgrade nginx to v4.2.0
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore

#742 Attach custom node policy to master nodes too
  internal/provisioner/kops_provisioner_cluster.go
Labels: kind/bug, release-note

#743 EKS Provisioner API and CLI support
  cmd/cloud/cluster.go
  cmd/cloud/server.go
  example_node_group_config.json
  go.mod
  go.sum
  internal/api/cluster.go
  internal/api/cluster_installation_test.go
  internal/api/cluster_test.go
  internal/api/common_test.go
  internal/api/context.go
  internal/api/events_test.go
  internal/store/cluster.go
  internal/store/group_dto_test.go
  model/cluster_request.go
Labels: release-note

#744 Add schema count in installation report command
  cmd/cloud/installation.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#745 Fix a bug in calico provisioning and make calico default CNI
  cmd/cloud/cluster.go
  internal/provisioner/kops_provisioner_cluster.go
Labels: 2: Dev Review, kind/bug, release-note

#746 Add server_lifetime and server_idle_timeout pgbouncer variables
  cmd/cloud/server.go
  internal/provisioner/pgbouncer.go
  model/multitenant_database.go
Labels: kind/feature, release-note

#752 Refactor PGBouncer config and add auth query option
  cmd/cloud/server.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/eks_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/pgbouncer.go
  internal/provisioner/pgbouncer_test.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  model/multitenant_database.go
Labels: 4: Reviews Complete, kind/feature, release-note

#754 [CLD-4414] Remove auth query flag in provisioner
  cmd/cloud/server.go
  internal/provisioner/pgbouncer.go
  internal/provisioner/pgbouncer_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#755 change auth_query of pgbouncer to not use the function
  internal/provisioner/pgbouncer.go
Labels: 4: Reviews Complete, release-note, kind/chore

#749 [MM-46849] Use rotator when resizing a cluster
  cmd/cloud/cluster.go
  internal/provisioner/kops_provisioner_cluster.go
  model/cluster_request.go
  model/kops_metadata.go
  model/kops_metadata_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#757 update sloth from v0.10.0 to v0.11.0
  manifests/sloth/sloth.yaml
Labels: 4: Reviews Complete, release-note
