Repository mattermost/mattermost-cloud, pull requests merged in 2022-02, with the labels that each got.

#606 Create Provisioner e2e job manifest
  e2e-deploy/e2e-job.yaml
Labels: release-note-none, kind/testing

#607 Expose base prometheus metrics on separate port
  build/Dockerfile
  cmd/cloud/server.go
  internal/api/api.go
  kubernetes/deployment.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#608 Add metrics for installation changes
  cmd/cloud/server.go
  internal/metrics/metrics.go
  internal/store/events.go
  internal/store/events_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/events_state_change.go
  model/time.go
Labels: 4: Reviews Complete, kind/feature, release-note

#609 Support multiple public hosted zones
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/route53.go
  internal/tools/aws/route53_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#610 Add cluster installation duration metrics
  cmd/cloud/server.go
  e2e/workflow/installation.go
  internal/metrics/metrics.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation.go
Labels: 2: Dev Review, kind/feature, release-note

#611 Use private zone id instead of name
  internal/tools/aws/route53.go
Labels: kind/bug, release-note-none

#612 [MM-42012] Remove stackrox utility from provisioner deployments
  cmd/cloud/cluster.go
  helm-charts/stackrox_values.yaml
  internal/api/request_test.go
  internal/provisioner/stackrox.go
  internal/provisioner/utility_group.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/deprecation, release-note

#613 [MM-41990] Update provisioner to work with new Gitlab repo utilities
  internal/provisioner/helm_utils.go
  model/cluster_utility.go
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore
