Repository mattermost/mattermost-cloud, pull requests merged in 2022-12, with the labels that each got.

#774 refinement of flag parsing (cloud cluster)
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/main.go
  cmd/cloud/table_printer.go
  cmd/cloud/utils.go
Labels: 4: Reviews Complete, release-note-none

#773 [MM-48554] Performance improvements on provisioner queries
  internal/store/migrations.go
Labels: 4: Reviews Complete, release-note

#770 [MM-48301/MM-48299] Upgrade EC2/VPC AWS SDK to v2
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/ec2.go
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/cluster_management_test.go
  internal/tools/aws/database.go
  internal/tools/aws/database_migration.go
  internal/tools/aws/database_migration_test.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/database_test.go
  internal/tools/aws/ec2.go
  internal/tools/aws/ec2_test.go
  internal/tools/aws/ec2_types.go
  internal/tools/aws/eks.go
  internal/tools/aws/general.go
  internal/tools/aws/helpers.go
  internal/tools/aws/rds.go
  internal/tools/aws/rds_test.go
  internal/tools/aws/route53.go
  internal/tools/aws/secret_test.go
  internal/tools/aws/session_test.go
  internal/tools/aws/tags.go
  internal/tools/aws/tags_test.go
  internal/tools/aws/vpc.go
Labels: 2: Dev Review, release-note

#778 move 'server' & 'dry-run' flags to global flagset
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/server.go
Labels: 4: Reviews Complete, release-note-none

#781 Fix to set values in Calico
  internal/provisioner/kops_provisioner_cluster.go
Labels: 2: Dev Review, kind/bug, release-note-none

#779 Remove deprecated database endpoints
  internal/api/databases.go
  internal/api/db_multitenant_database_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#783 [MM-48880] Added a flag for showing tags while listing
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
Labels: 2: Dev Review, kind/feature, release-note

#784 [MM-48794] Set additional ENVs for Go & Process metrics
  internal/provisioner/kops_provisioner_cluster.go
Labels: 2: Dev Review, release-note-none

#782 CLD 4515 sync pgbouncer configmap
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/eks_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/aws/constants.go
Labels: 4: Reviews Complete, release-note-none

#776 [MM-48593] Create Prometheus SLOs per cluster
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/cluster_sli.go
  internal/provisioner/kops_provisioner_installation_sli.go
  internal/provisioner/sloth.go
Labels: release-note

#777 [MM-48583] Create SLIs/SLOs per ring via provisioner
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/mocks/model/installation_database.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/cluster_sli.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/sloth.go
  internal/supervisor/db_migration_test.go
  internal/supervisor/installation_test.go
  model/installation_database.go
Labels: release-note

#780 Refinement of flag parsing
  cmd/cloud/cluster.go
  cmd/cloud/cluster_annotation.go
  cmd/cloud/cluster_annotation_flag.go
  cmd/cloud/cluster_installation.go
  cmd/cloud/cluster_installation_flag.go
Labels: 2: Dev Review, release-note-none

#785 [MM-46451] Avoiding unnecessary CloudFlare requests
  internal/tools/cloudflare/dns.go
  internal/tools/cloudflare/dns_test.go
Labels: 4: Reviews Complete, release-note-none

#786 Refinement of flag parsing (cloud installation)
  cmd/cloud/installation.go
  cmd/cloud/installation_flag.go
  cmd/cloud/main.go
Labels: 2: Dev Review, release-note-none

#792 fix logger using pointer
  internal/tools/aws/cluster_management.go
Labels: release-note-none

#789 [CLD-4667] Allow metrics for Boards and Playbooks
  manifests/network-policies/mm-installation-netpol.yaml
Labels: kind/feature, release-note

#794 Add custom 7d window to sloth.
  manifests/sloth/sloth.yaml
Labels: 4: Reviews Complete, release-note, kind/refactor

#791 Refinement of flag parsing (cloud installation) 2/2
  cmd/cloud/backup.go
  cmd/cloud/backup_flag.go
  cmd/cloud/installation.go
  cmd/cloud/installation_annotation.go
  cmd/cloud/installation_annotation_flag.go
  cmd/cloud/installation_dns.go
  cmd/cloud/installation_dns_flags.go
  cmd/cloud/installation_operation.go
  cmd/cloud/installation_operation_db_migration.go
  cmd/cloud/installation_operation_db_migration_flag.go
  cmd/cloud/installation_operation_restoration.go
  cmd/cloud/installation_operation_restoration_flag.go
Labels: 2: Dev Review, release-note-none

#787 Set priorities to 'creation-requested' and 'creation-in-progress'
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
  internal/supervisor/installation_test.go
  model/cluster_states.go
Labels: 4: Reviews Complete, kind/feature, release-note

#793 [MM-49091] Refinement of flag parsing (cloud group)
  cmd/cloud/group.go
  cmd/cloud/group_annotation.go
  cmd/cloud/group_annotation_flag.go
  cmd/cloud/group_flag.go
  cmd/cloud/main.go
Labels: 2: Dev Review, release-note-none

#788 [MM-41914] Added metrics for cluster change
  cmd/cloud/server.go
  internal/metrics/metrics.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
Labels: 2: Dev Review, kind/feature, release-note

#796 [CLD-4714] Delete helm chart to clean up LB resources
  internal/provisioner/kubecost.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/thanos.go
Labels: 2: Dev Review, release-note-none

#799 [MM-48302] Upgrade DynamoDB to SDK v2
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/dynamodb.go
  internal/testlib/aws.go
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/dynamodb.go
  internal/tools/aws/dynamodb_test.go
  internal/tools/aws/dynamodb_types.go
Labels: 4: Reviews Complete, release-note

#798 [Mm 49246] Refinement of flag parsing (cloud database)
  cmd/cloud/databases.go
  cmd/cloud/databases_flag.go
  cmd/cloud/main.go
Labels: 2: Dev Review, release-note-none

#801 [MM-49335] Refinement of flag parsing
  cmd/cloud/main.go
  cmd/cloud/schema.go
  cmd/cloud/schema_flag.go
  cmd/cloud/security.go
  cmd/cloud/security_flag.go
  cmd/cloud/webhook.go
  cmd/cloud/webhook_flag.go
Labels: 2: Dev Review, release-note-none

#795 [MM-49155] Set priorities for creation-specific actions.
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/cluster_installation_states.go
  model/installation_states.go
Labels: 2: Dev Review, release-note

#804 Sanitize resource name for prometheus SLIs
  internal/provisioner/cluster_sli.go
  internal/tools/utils/strings.go
  internal/tools/utils/strings_test.go
Labels: kind/bug, release-note-none

#805 [MM-49349] Refinement of flag parsing [final part]
  cmd/cloud/completion.go
  cmd/cloud/dashboard.go
  cmd/cloud/dashboard_flag.go
  cmd/cloud/events.go
  cmd/cloud/events_flag.go
  cmd/cloud/events_subscription.go
  cmd/cloud/events_subscription_flag.go
  cmd/cloud/main.go
  cmd/cloud/workbench.go
  cmd/cloud/workbench_flag.go
Labels: 4: Reviews Complete, release-note-none

#797 [MM-48300] Update Route53 to SDK v2
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/route53.go
  internal/tools/aws/client.go
  internal/tools/aws/route53.go
  internal/tools/aws/route53_test.go
  internal/tools/aws/route53_types.go
Labels: 4: Reviews Complete, release-note

#803 [MM-48525] AWS SDK v2 migration - IAM
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/iam.go
  internal/tools/aws/client.go
  internal/tools/aws/iam.go
  internal/tools/aws/iam_types.go
  internal/tools/aws/secrets_manager.go
Labels: 4: Reviews Complete, release-note

#808 Cleanup for PrintJSON & DryRun
  cmd/cloud/backup.go
  cmd/cloud/cluster.go
  cmd/cloud/cluster_annotation.go
  cmd/cloud/cluster_installation.go
  cmd/cloud/databases.go
  cmd/cloud/events_subscription.go
  cmd/cloud/flags.go
  cmd/cloud/group.go
  cmd/cloud/installation.go
  cmd/cloud/installation_dns.go
  cmd/cloud/installation_operation_db_migration.go
  cmd/cloud/installation_operation_restoration.go
  cmd/cloud/table_printer.go
  cmd/cloud/utils.go
Labels: 2: Dev Review, release-note-none

#800 [MM-48303] Update S3 to SDK v2
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/s3.go
  internal/tools/aws/client.go
  internal/tools/aws/helpers.go
  internal/tools/aws/s3.go
  internal/tools/aws/s3_types.go
Labels: 4: Reviews Complete, release-note

#811 [MM-38163] Retry to report AWAT with exponential backoff
  go.mod
  go.sum
  internal/supervisor/import.go
  internal/tools/utils/backoff.go
Labels: 2: Dev Review, kind/bug, release-note-none

#812 [MM-49373] Set logger to avoid panic
  internal/provisioner/nginx_internal.go
Labels: 2: Dev Review, kind/bug, release-note-none

#813 [MM-49373] Ensure helm deployment is generated properly
  internal/provisioner/cloudprober.go
  internal/provisioner/fluentbit.go
  internal/provisioner/helm_utils.go
  internal/provisioner/kubecost.go
  internal/provisioner/metrics_server.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/node_problem_detector.go
  internal/provisioner/pgbouncer.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/promtail.go
  internal/provisioner/rtcd.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/provisioner/velero.go
Labels: 2: Dev Review, release-note-none

#814 [MM-49377] Fix bucket not being sent in batch delete
  internal/tools/aws/s3.go
Labels: release-note-none

#816 Use PersistentFlag only when needed.
  cmd/cloud/cluster_flag.go
  cmd/cloud/dashboard_flag.go
  cmd/cloud/server_flag.go
Labels: 2: Dev Review, release-note

#815 [MM-49373] Bucket and Helm deletion fixes
  internal/mocks/aws-sdk/s3.go
  internal/provisioner/helm_utils.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/prometheus_operator.go
  internal/tools/aws/s3.go
  internal/tools/aws/s3_types.go
Labels: 2: Dev Review, release-note-none

#818 Use value-type data to fix an erroneous pointer reference.
  internal/tools/aws/route53.go
Labels: kind/bug, release-note

#817 [MM-29718] Allow env var to set every cloud flag
  cmd/cloud/main.go
Labels: 2: Dev Review, kind/feature, release-note
