Repository mattermost/mattermost-cloud, pull requests merged in 2022-01, with the labels that each got.

#590 Use mattermost/kube-spot-termination-notice-handler container
  manifests/k8s-spot-termination-handler/k8s-spot-termination-handler.yaml
Labels: 4: Reviews Complete, release-note, kind/chore

#592 Close database connections in some unit tests
  internal/events/delivery.go
  internal/events/delivery_test.go
  internal/events/producer_test.go
  internal/supervisor/backup_test.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/cluster_test.go
  internal/supervisor/group_test.go
  internal/supervisor/installation_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#591 Redact AWS requests parameters
  internal/tools/aws/session.go
  internal/tools/aws/session_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#595 [MM-41008] Add support for Promtail utility in provisioner
  cmd/cloud/cluster.go
  helm-charts/promtail_values.yaml
  internal/api/request_test.go
  internal/provisioner/promtail.go
  internal/provisioner/utility_group.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: kind/feature, release-note

#589 Add checks for Provisioner events to e2e cluster tests
  e2e/pkg/cluster.go
  e2e/pkg/eventstest/handler.go
  e2e/pkg/eventstest/handler_test.go
  e2e/pkg/installation.go
  e2e/pkg/webhook_handler.go
  e2e/tests/cluster/cluster_test.go
  e2e/tests/cluster/steps.go
  e2e/tests/cluster/suite.go
  e2e/workflow/cluster.go
  e2e/workflow/db_migration.go
  e2e/workflow/engine.go
  e2e/workflow/events.go
  e2e/workflow/installation.go
Labels: 4: Reviews Complete, kind/feature, release-note

#594 Add Event Listener tool
  cmd/tools/README.md
  cmd/tools/event-listener/main.go
Labels: 4: Reviews Complete, kind/feature, release-note

#597 Revert "Upgrade kops to 1.21 and terraform to 0.15"
  Makefile
  README.md
Labels: kind/feature, release-note-none

#598 Upgrade kops to 1.21 and terraform to 0.13
  Makefile
  README.md
Labels: kind/feature, release-note

#600 Cleanup Teleport utility destruction
  internal/provisioner/teleport.go
Labels: kind/cleanup, release-note

#599 Improve import supervisor logging
  internal/metrics/metrics.go
  internal/supervisor/import.go
Labels: 2: Dev Review, kind/cleanup, release-note-none

#601 Build cluster e2e tests image as part of CI
  .circleci/config.yml
  Makefile
  build/Dockerfile.e2e
  scripts/push-docker-pr.sh
  scripts/push-docker.sh
Labels: kind/feature, release-note

#603 Skip DB cleanup if database is marked as deleted
  internal/tools/aws/database_multitenant.go
Labels: kind/bug, release-note

#602 Make better Installation DNS configuration in e2e
  e2e/pkg/dns.go
  e2e/tests/cluster/suite.go
  e2e/tests/dbmigration/suite.go
  e2e/workflow/cluster.go
  e2e/workflow/db_migration.go
  e2e/workflow/installation.go
Labels: kind/bug, release-note

#604 [MM-41366] Fix wrong Teleport kube agent default name
  internal/provisioner/teleport.go
Labels: release-note
