Repository mattermost/mattermost-cloud, pull requests merged in 2023-04, with the labels that each got.

#897 [MM-51737] Cluster Installation Status endpoint
  cmd/cloud/cluster_installation.go
  cmd/cloud/cluster_installation_flag.go
  e2e/pkg/installation.go
  e2e/tests/cluster/steps.go
  e2e/workflow/installation.go
  internal/api/cluster_installation.go
  internal/api/common_test.go
  internal/api/context.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/exec.go
  model/client.go
  model/cluster_installation.go
Labels: 2: Dev Review, release-note-none

#900 Bump helm to v3.11.2
  Makefile
  README.md
Labels: 2: Dev Review, release-note, kind/chore

#903 Fix invalid Grafana link template
  e2e/pkg/webhook.go
Labels: kind/bug, release-note-none

#906 Create Nodegroups in an EKS cluster
  clusterdictionary/size.go
  cmd/cloud/cluster.go
  cmd/cloud/nodegroup.go
  cmd/cloud/nodegroup_flag.go
  internal/api/cluster.go
  internal/provisioner/eks_provisioner.go
  internal/supervisor/cluster.go
  model/client.go
  model/cluster_request.go
  model/cluster_states.go
  model/eks_metadata.go
Labels: 2: Dev Review, release-note-none

#909 Remove kube-spot-termination-handler
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/provisioner/cluster_provisioning.go
  manifests/k8s-spot-termination-handler/k8s-spot-termination-handler.yaml
  model/cluster.go
Labels: kind/cleanup, release-note

#907 [CLD-5436]Add vpcID tag to nginx LB
  internal/mocks/aws-tools/client.go
  internal/provisioner/utility/nginx.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
Labels: 2: Dev Review, kind/feature, release-note-none

#913 deps: update operator to v1.20.1
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 2: Dev Review, kind/feature, release-note
