Repository mattermost/mattermost-cloud, pull requests merged in 2023-02, with the labels that each got.

#850 [MM-49890] Make e2e tests KopsAMI parameter optional
  e2e/tests/cluster/suite.go
Labels: 4: Reviews Complete, kind/bug, release-note-none

#849 [MM-49782] Reduce replicasets kept in cluster via Mattermost operator from 6 to 2
  go.mod
  go.sum
  internal/provisioner/cluster_installation_provisioner.go
  manifests/operator-manifests/mattermost/crds/mm_mattermost_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, kind/feature, release-note

#847 [MM-49747] Check installation update flags changes
  cmd/cloud/installation.go
  cmd/cloud/installation_flag.go
Labels: 4: Reviews Complete, kind/bug, release-note

#840 [MM-49713] Enable rotator on resize operations when kops require rolling-updates
  internal/provisioner/kops_provisioner_cluster.go
  internal/tools/kops/cluster.go
  internal/tools/kops/run.go
Labels: 2: Dev Review, release-note

#851 Fix bug to read server flag in cloud security command
  cmd/cloud/security.go
  go.mod
  go.sum
Labels: 2: Dev Review, kind/bug, release-note

#852 replaced incorrect errors pkg
  e2e/pkg/webhook.go
  go.mod
Labels: 4: Reviews Complete, kind/bug, release-note-none

#853 Warn and continue if it fails to destroy utilities
  internal/provisioner/utility_group.go
Labels: 2: Dev Review, release-note-none

#854 [CLD-5000, CLD-5010] Update metrics-server, node-problem-detector
  internal/api/request_test.go
  internal/provisioner/metrics_server_test.go
  internal/provisioner/node_problem_detector_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#855 [MM-50387] Decrease Master Instance type for sizeAlefDev & sizeAlef500
  clusterdictionary/size.go
  clusterdictionary/size_test.go
Labels: 2: Dev Review, release-note

#858 Fix workbench command removing workbench directory
  cmd/cloud/workbench.go
Labels: 4: Reviews Complete, kind/bug, release-note

#859 Bump operator version to v1.20.0-rc.2
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 2: Dev Review, release-note, kind/chore

#861 fix: set up common provisioner logger
  internal/provisioner/eks_provisioner_cluster.go
  internal/provisioner/kops_provisioner.go
Labels: 2: Dev Review, kind/bug, release-note

#862 Increase time of command running
  internal/provisioner/kops_provisioner_cluster_installation.go
Labels: release-note

#857 [MM-50375] Revert Prometheus SLO for Rings and Clusters
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/mocks/model/installation_database.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/cluster_sli.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/provisioner_installation_sli.go
  internal/provisioner/sloth.go
  internal/provisioner/thanos.go
  internal/supervisor/db_migration_test.go
  internal/supervisor/installation_test.go
  model/installation_database.go
Labels: kind/bug, release-note

#865 Fix DB migration supervisor shutdown log
  internal/supervisor/db_migration.go
Labels: 4: Reviews Complete, kind/bug, release-note

#864 Resolve issues with the EKS cluster creation.
  .github/workflows/ci.yml
  Makefile
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/main.go
  e2e/pkg/cluster.go
  e2e/pkg/installation.go
  e2e/tests/cluster/steps.go
  e2e/tests/cluster/suite.go
  e2e/workflow/cluster.go
  e2e/workflow/db_migration.go
  e2e/workflow/installation.go
  internal/api/cluster.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/eks_provisioner_cluster.go
  internal/provisioner/eks_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/ec2.go
  internal/tools/aws/ec2_types.go
  internal/tools/aws/eks.go
  k8s/manifest.go
  k8s/namespaces.go
  k8s/poddisruptionbudget.go
  k8s/storage_class.go
  manifests/eks/calico-eks.yaml
  manifests/storageclass.yaml
  model/cluster.go
  model/cluster_eks.go
  model/cluster_request.go
  model/cluster_states.go
Labels: 2: Dev Review, release-note-none

#866 [MM-50727] Properly log scheduler errors
  cmd/cloud/server.go
  internal/supervisor/scheduler.go
  internal/supervisor/scheduler_test.go
Labels: kind/bug, release-note

#867 Bump version to kube-spot-termination-notice-handler
  manifests/k8s-spot-termination-handler/k8s-spot-termination-handler.yaml
Labels: release-note, kind/chore

#860 [MM-50487] Enable EKS cluster support without server flag
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/api/cluster.go
  internal/api/context.go
  internal/provisioner/backup_restore.go
  internal/provisioner/backup_restore_test.go
  internal/provisioner/cluster.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/eks_provisioner_backup_restore.go
  internal/provisioner/eks_provisioner_cluster.go
  internal/provisioner/eks_provisioner_cluster_installation.go
  internal/provisioner/k8s.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_backup_restore.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_test.go
  internal/provisioner/kops_utils.go
  internal/provisioner/provisioner.go
  internal/supervisor/backup.go
  internal/supervisor/backup_test.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/cluster_test.go
  internal/supervisor/db_migration.go
  internal/supervisor/db_migration_test.go
  internal/supervisor/import.go
  internal/supervisor/installation.go
  internal/supervisor/installation_db_restoration.go
  internal/supervisor/installation_db_restoration_test.go
  internal/supervisor/installation_test.go
  internal/supervisor/provisioner.go
Labels: 2: Dev Review, release-note

#870 [CLD-5022]Add external-snapshotter Deployment
  internal/provisioner/cluster_provisioning.go
  manifests/external-snapshotter/external-snapshotter.yaml
Labels: kind/feature, release-note
