Repository mattermost/mattermost-cloud, pull requests merged in 2023-01, with the labels that each got.

#806 [MM-49345] AWS SDK v2 migration - RDS, KMS, GT
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-sdk/rds.go
  internal/mocks/aws-sdk/resource_tagging.go
  internal/tools/aws/client.go
  internal/tools/aws/database.go
  internal/tools/aws/database_migration.go
  internal/tools/aws/database_migration_test.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/database_test.go
  internal/tools/aws/general.go
  internal/tools/aws/helpers_sql.go
  internal/tools/aws/kms.go
  internal/tools/aws/kms_types.go
  internal/tools/aws/rds.go
  internal/tools/aws/rds_test.go
  internal/tools/aws/rds_types.go
  internal/tools/aws/resource_tagging.go
  internal/tools/aws/resource_tagging_test.go
  internal/tools/aws/resource_tagging_types.go
  internal/tools/aws/tags.go
  internal/tools/aws/tags_test.go
Labels: 4: Reviews Complete, release-note

#821 [CLD-4712] Cleanup of Kubecost deployments
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  helm-charts/kubecost_values.yaml
  internal/api/request_test.go
  internal/provisioner/kubecost.go
  internal/provisioner/utility_group.go
  model/cluster.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#802 [MM-48305] AWS SDK v2 migration - Secrets Manager
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/tools/aws/client.go
  internal/tools/aws/database_external.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/database_test.go
  internal/tools/aws/secrets_manager.go
  internal/tools/aws/secrets_mangager_types.go
  internal/tools/aws/session_test.go
Labels: 4: Reviews Complete, release-note

#809 [MM-49359] AWS SDK v2 Migration - EKS
  go.mod
  go.sum
  internal/mocks/aws-tools/client.go
  internal/provisioner/eks_provisioner_cluster.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/eks.go
  internal/tools/aws/eks_types.go
  model/cluster_eks.go
Labels: 4: Reviews Complete, release-note

#824 fix: incorrect RDS secret name
  internal/tools/aws/database.go
  internal/tools/aws/secrets_manager.go
Labels: kind/bug, release-note-none

#825 [MM-49445] Added stacktrace in Error log
  cmd/cloud/logger.go
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
Labels: 2: Dev Review, release-note-none

#810 [MM-48304] AWS SDK v2 migration (final cleanup)
  cmd/cloud/installation.go
  cmd/cloud/server.go
  go.mod
  go.sum
  internal/mocks/aws-sdk/doc.go
  internal/mocks/aws-sdk/sts.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/client_test.go
  internal/tools/aws/config.go
  internal/tools/aws/database_migration_test.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/errors.go
  internal/tools/aws/filestore.go
  internal/tools/aws/filestore_bifrost.go
  internal/tools/aws/filestore_multitenant.go
  internal/tools/aws/general.go
  internal/tools/aws/helpers.go
  internal/tools/aws/resource_tagging_test.go
  internal/tools/aws/s3.go
  internal/tools/aws/session.go
  internal/tools/aws/session_test.go
  internal/tools/aws/sts.go
  internal/tools/aws/sts_types.go
  internal/tools/terraform/plan.go
Labels: release-note

#823 [MM-49378] Added Nginx SLO for Enterprise customer
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/nginx_sli.go
Labels: 4: Reviews Complete, release-note

#827 Add Perseus database type
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  go.mod
  go.sum
  internal/mocks/aws-sdk/kms.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/cluster_provisioning.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/constants.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_perseus.go
  internal/tools/aws/helpers.go
  internal/tools/aws/helpers_sql.go
  internal/tools/aws/kms.go
  internal/tools/aws/kms_types.go
  internal/tools/utils/utils.go
  manifests/operator-manifests/mattermost/role.yaml
  manifests/perseus/perseus.yaml
  model/installation_database.go
  model/installation_database_test.go
Labels: 2: Dev Review, kind/feature, release-note

#826 [MM-49396] Add Name tag in ELB resources
  go.mod
  go.sum
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_utils.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/elb.go
  internal/tools/aws/elb_types.go
Labels: 2: Dev Review, release-note-none

#831 Update Perseus utility
  manifests/perseus/perseus.yaml
Labels: 4: Reviews Complete, release-note, kind/chore

#832 Fix latest tag docker push and ignore CD on master
  .github/workflows/cd.yml
  scripts/push-docker.sh
Labels: 4: Reviews Complete, kind/bug, release-note-none

#834 [MM-49661] Fixed retrieval of DNS Record Sets
  internal/provisioner/thanos.go
  internal/tools/aws/route53.go
Labels: 4: Reviews Complete, release-note

#833 Tag docker images with latest tag
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  scripts/push-docker.sh
Labels: 2: Dev Review, release-note-none

#836 Disable rotation on cluster resize
  internal/provisioner/kops_provisioner_cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note-none

#837 Fix docker push for tags
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  scripts/push-docker.sh
Labels: 2: Dev Review, kind/bug, release-note-none

#830 [MM-49490] Notify E2E test result via Mattermost webhook
  e2e/pkg/installation.go
  e2e/pkg/webhook.go
  e2e/tests/cluster/cluster_test.go
  e2e/tests/cluster/suite.go
  e2e/workflow/installation.go
Labels: 4: Reviews Complete, release-note-none

#838 Perform final route53 record deletion validation
  internal/tools/aws/route53.go
Labels: 2: Dev Review, kind/cleanup, release-note

#839 AWS multitenant database cleanup and tests
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_multitenant_test.go
  internal/tools/aws/database_perseus.go
  internal/tools/aws/helpers.go
  internal/tools/aws/helpers_sql.go
  internal/tools/aws/helpers_test.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#842 fix: shadowing errors on perseus
  internal/tools/aws/database_perseus.go
Labels: kind/bug, release-note-none

#843 docs: added diffutils reference for macos
  README.md
Labels: release-note-none

#844 [MM-49778] Fix kops creating a temporary file instead of a directory for the kops cache
  internal/tools/kops/cmd.go
  internal/tools/kops/export.go
Labels: kind/bug, release-note

#841 Add installation deletion pending expiration control
  cmd/cloud/installation.go
  cmd/cloud/installation_flag.go
  cmd/cloud/server.go
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  internal/store/migrations.go
  internal/supervisor/installation_deletion.go
  internal/supervisor/installation_deletion_test.go
  model/client.go
  model/installation.go
  model/installation_request.go
  model/installation_request_test.go
  model/installation_states.go
  model/multitenant_database.go
  model/time.go
Labels: 2: Dev Review, kind/feature, release-note

#846 [CLD-4832] Remove proxy-real-ip-cidr config using local VPC cidr
  internal/provisioner/nginx.go
Labels: release-note

#845 [MM-49410] refactor: err number to proper names
  cmd/cloud/installation.go
  cmd/cloud/server.go
  cmd/cloud/workbench.go
  cmd/tools/ctest/test.go
  internal/api/cluster_installation.go
  internal/api/cluster_installation_test.go
  internal/api/cluster_test.go
  internal/api/db_multitenant_database.go
  internal/api/db_multitenant_database_test.go
  internal/api/events_subscription_test.go
  internal/api/group_test.go
  internal/api/installation.go
  internal/api/installation_backup_test.go
  internal/api/installation_db_migration_test.go
  internal/api/installation_test.go
  internal/events/producer_test.go
  internal/provisioner/backup_restore_test.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/store/annotation_test.go
  internal/store/cluster_installation.go
  internal/store/cluster_installation_test.go
  internal/store/db_helpers_test.go
  internal/store/events_subscription_test.go
  internal/store/group_test.go
  internal/store/installation_backup_test.go
  internal/store/installation_db_migration_test.go
  internal/store/installation_db_restoration_operation_test.go
  internal/store/installation_dns_test.go
  internal/store/installation_test.go
  internal/store/migrations.go
  internal/supervisor/import.go
  internal/supervisor/installation.go
  internal/supervisor/installation_db_restoration.go
  internal/tools/aws/database.go
  internal/tools/aws/s3.go
  internal/tools/aws/secrets_manager.go
Labels: 4: Reviews Complete, release-note-none, kind/refactor
