Repository mattermost/mattermost-cloud, pull requests merged in 2023-05, with the labels that each got.

#915 [MM-52578] Resolved panic for missing VPC
  internal/mocks/aws-tools/client.go
  internal/provisioner/utility/nginx.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
Labels: 2: Dev Review, kind/bug, release-note-none

#919 Update bifrost to v1.0.4 which add parameters which expose config settings for server timeout
  manifests/bifrost/bifrost.yaml
Labels: release-note

#918 [MM-51246] fix: recover old utility version parsing fallback
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 2: Dev Review, kind/feature, release-note

#916 [MM-52602] Don't allow cluster deletion If any installation exists.
  internal/api/cluster.go
Labels: 2: Dev Review, release-note-none

#911 [MM-52418] default single tenant database instance size
  model/single_tenant_database.go
  model/single_tenant_database_test.go
Labels: kind/bug, release-note

#920 [MM-52658] fix: raised e2e installation timeout to 15m
  e2e/pkg/installation.go
Labels: 2: Dev Review, kind/feature, release-note

#910 [MM-51736] Delete Nodegroup from an EKS cluster
  cmd/cloud/cluster.go
  cmd/cloud/nodegroup.go
  cmd/cloud/nodegroup_flag.go
  internal/api/cluster.go
  internal/provisioner/eks_provisioner.go
  internal/provisioner/kops_provisioner.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
  model/client.go
  model/cluster_states.go
  model/eks_metadata.go
Labels: 2: Dev Review, release-note-none

#922 Set logger output to os.Stdout
  cmd/cloud/logger.go
Labels: 2: Dev Review, release-note

#905 [MM-51582] Upgrade all dependencies
  go.mod
  go.sum
  internal/provisioner/backup_restore_operator_test.go
  internal/provisioner/exec.go
  internal/tools/cloudflare/client.go
  internal/tools/cloudflare/dns.go
  internal/tools/cloudflare/dns_test.go
  internal/tools/cloudflare/mocks.go
  internal/tools/cloudflare/noop.go
  k8s/helpers.go
  k8s/manifest.go
Labels: 2: Dev Review, kind/feature, release-note

#926 Upgrade kops to 1.24
  Makefile
Labels: 4: Reviews Complete, release-note, kind/chore

#927 Upgrade k8s rotator dependency
  go.mod
  go.sum
Labels: 2: Dev Review, 2: Infra Review, release-note-none
