Repository mattermost/mattermost-cloud, pull requests merged in 2023-11, with the labels that each got.

#980 [CLD-6529] Implement Enabled Check for Allowed IP Ranges + a few refactors
  cmd/cloud/server_flag.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_installation_provisioner_test.go
  internal/provisioner/provisioner.go
  model/ingress.go
  model/ingress_test.go
  model/installation.go
  model/installation_test.go
Labels: 4: Reviews Complete, release-note-none

#981 Add group nil check for SLI checks
  internal/provisioner/cluster_installation_provisioner.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#982 Add webhook header counts to table output
  cmd/cloud/webhook.go
  model/types.go
Labels: release-note

#984 Fix potential panic on unsafe access of installation.AllowedIPRanges
  model/installation_request.go
  model/installation_request_test.go
Labels: release-note-none

#983 Support arbitrary domain creation for installations
  cmd/cloud/installation.go
  cmd/cloud/installation_dns.go
  cmd/cloud/installation_dns_flags.go
  cmd/cloud/server.go
  internal/api/common_test.go
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_dns.go
  internal/api/installation_dns_test.go
  internal/store/installation_dns.go
  internal/store/installation_dns_test.go
  internal/testutil/dns.go
  internal/tools/cloudflare/dns.go
  model/client.go
  model/installation.go
  model/installation_dns.go
  model/installation_dns_test.go
Labels: 4: Reviews Complete, kind/feature, release-note
