Repository mattermost/mattermost-cloud, pull requests merged in 2023-08, with the labels that each got.

#954 Upgrade Bifrost to v1.0.6
  manifests/bifrost/bifrost.yaml
Labels: 2: Dev Review, release-note

#955 [CLD-6035] Fix potential for installation (and therefore cluster) to leak after E2E failure
  e2e/tests/installation/installation_test.go
Labels: 4: Reviews Complete, release-note-none

#956 Add Cluster Installation nil check for getClusterForClusterInstallation
  internal/supervisor/common.go
  internal/supervisor/common_test.go
Labels: 2: Dev Review, kind/bug, release-note

#957 [CLD-6070]Bump node-problem-detector chart to v2.3.5
  internal/api/request_test.go
  internal/provisioner/utility/node_problem_detector_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: kind/feature, release-note

#961 Add Grafana Annotations
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  go.mod
  go.sum
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
  internal/tools/aws/client.go
  internal/tools/grafana/client.go
  internal/tools/grafana/grafana_client.go
  internal/tools/grafana/noop_client.go
  internal/tools/grafana/tags.go
Labels: 4: Reviews Complete, release-note

#962 Update terraform version from 1.0.7 to 1.5.5
  Makefile
  README.md
Labels: release-note

#964 Add new database report tooling
  cmd/cloud/databases.go
  cmd/cloud/databases_flag.go
  cmd/cloud/workbench.go
  model/client.go
Labels: 2: Dev Review, release-note

#965 Add API endpoint to delete logical databases
  cmd/cloud/databases.go
  cmd/cloud/databases_flag.go
  internal/api/context.go
  internal/api/db_logical_database.go
  internal/api/db_logical_database_test.go
  internal/api/db_multitenant_database_test.go
  internal/store/db_database_schema.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/helpers_sql.go
  internal/tools/aws/rds.go
  model/client.go
Labels: 2: Dev Review, kind/feature, release-note

#967 Attach cluster policies earlier on updates
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/provisioner_utils.go
Labels: 4: Reviews Complete, kind/feature, release-note

#968 Bump rotator to fix drain and termination bugs of previous version
  go.mod
  go.sum
Labels: kind/bug, release-note
