Repository mattermost/mattermost-cloud, pull requests merged in 2023-10, with the labels that each got.

#970 [CLD-6304] IP Validator for IP Filtering + Storage Changes for UX
  cmd/cloud/installation_flag.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/store/migrations.go
  model/installation.go
  model/installation_request.go
  model/installation_request_test.go
  model/installation_test.go
Labels: release-note-none

#973 [CLD-6415] Allow MSteams metrics port in network policy
  manifests/network-policies/mm-installation-netpol.yaml
Labels: kind/feature, release-note

#974 Add `--deletion-locked` installation list filter flag
  cmd/cloud/installation.go
  cmd/cloud/installation_flag.go
  internal/api/common_test.go
  internal/api/helpers.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  internal/store/installation_test.go
  model/installation.go
  model/installation_request.go
Labels: 2: Dev Review, kind/feature, release-note

#972 Support AWS KMS key
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  internal/api/cluster_test.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_utils.go
  internal/supervisor/installation.go
  internal/tools/grafana/grafana_client.go
  internal/tools/grafana/noop_client.go
  internal/tools/kops/instance_groups.go
  model/cluster.go
  model/cluster_request.go
  model/cluster_request_test.go
  model/kops_metadata.go
  model/provisioner_metadata.go
Labels: 4: Reviews Complete, release-note

#976 Update Mattermost Operator to v1.21.0-rc.2
  manifests/operator-manifests/mattermost/crds/mm_mattermost_crd.yaml
  manifests/operator-manifests/mattermost/operator.yaml
  manifests/operator-manifests/mattermost/role.yaml
Labels: 2: Dev Review, 2: Infra Review, release-note

#977 Fix installation hibernation ingress config
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_installation_provisioner_test.go
Labels: kind/bug, release-note

#978 Add lock information to installation reports
  cmd/cloud/installation.go
Labels: 4: Reviews Complete, release-note
