Repository mattermost/mattermost-cloud, pull requests merged in 2023-06, with the labels that each got.

#929 Bump rotator to fix naming convention issues in kops 1.24
  go.mod
  go.sum
Labels: kind/bug, release-note

#921 [MM-51707] Drop SQLite support
  .github/workflows/ci.yml
  Makefile
  cmd/cloud/installation_flag.go
  cmd/cloud/schema_flag.go
  cmd/cloud/server_flag.go
  go.mod
  internal/store/driver.go
  internal/store/events_subscription.go
  internal/store/helpers.go
  internal/store/migrations.go
  internal/store/store.go
  internal/store/testing.go
  model/aws_metadata.go
  model/cluster_utility.go
  model/eks_metadata.go
  model/kops_metadata.go
  model/types.go
  model/types_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#932 Onboarding adjustments
  Makefile
  README.md
  build/localdev/create-database.sql
  docker-compose.yml
Labels: 4: Reviews Complete, release-note-none

#933 [CLD-5737] Update Single Tenant PG Default Version to 13.10
  internal/tools/aws/constants.go
Labels: 2: Dev Review, release-note

#940 Fix CI/CD mock check
  .github/workflows/ci.yml
  Makefile
Labels: release-note-none

#937 [CLD-5720] Update Golang and Alpine versions to latest
  Makefile
  build/Dockerfile
  build/Dockerfile.e2e
  go.mod
  internal/supervisor/group.go
  internal/tools/aws/rds.go
  model/id.go
  model/password.go
  scripts/ensure_golangci-lint.sh
Labels: 4: Reviews Complete, release-note

#938 Cleanup README and add PostgreSQL information
  README.md
  cmd/cloud/server.go
Labels: release-note

#941 [CLD-5917]Bump bifrost version
  manifests/bifrost/bifrost.yaml
Labels: release-note
