Repository mattermost/mattermost-cloud, pull requests merged in 2023-07, with the labels that each got.

#943 [MM-5945] Add support for installation deletion locks
  cmd/cloud/security.go
  internal/api/context.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/api/security.go
  internal/store/installation.go
  internal/store/migrations.go
  model/client.go
  model/installation.go
  model/installation_request.go
Labels: 4: Reviews Complete, release-note

#945 Move E2E docker entrypoint to shell script
  build/Dockerfile.e2e
  build/bin-e2e/entrypoint
Labels: 4: Reviews Complete, kind/bug, release-note

#946 [CLD-6011] Update Thanos secret to support S3 encryption, upgrade default Prometheus and Fluentbit versions
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/utility/prometheus_operator.go
  model/cluster_utility.go
Labels: 4: Reviews Complete, kind/feature, release-note

#948 Fix the prometheus sidecar aws_sdk_auth variable
  internal/provisioner/utility/prometheus_operator.go
Labels: 4: Reviews Complete, kind/bug, release-note

#947 [CLD-6012]Update metrics server
  cloud.db-old
  internal/api/request_test.go
  internal/provisioner/utility/metrics_server_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: kind/feature, release-note

#953 Decrease rotator defaults
  cmd/cloud/cluster.go
Labels: release-note, kind/chore
