Repository mattermost/mattermost-cloud, pull requests merged in 2023-12, with the labels that each got.

#989 cld-6744: Upgrade cloudprober
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#990 cld-6744: Upgrade node-problem-detector
  internal/api/request_test.go
  internal/provisioner/utility/node_problem_detector_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#992 cld-6746: Upgrade external-snapshotter to version 6.3.2
  manifests/external-snapshotter/external-snapshotter.yaml
Labels: release-note

#993 cld-6746: Upgrade velero
  internal/api/request_test.go
  internal/provisioner/utility/velero.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#995 Revert "cld-6493: Update kops version from 1.25.4 to 1.26.6"
  Makefile
  README.md
Labels: kind/feature, release-note

#996 [CLD-6493]Upgrade kops to 1.27
  Makefile
  README.md
  internal/provisioner/kops_provisioner.go
Labels: kind/feature, release-note

#998 [CLD-6726] Upgrade Promtail default Helm version
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, release-note, kind/chore

#999 [CLD-6852]Disable by default minio and mysql operator
  cmd/cloud/server_flag.go
Labels: kind/feature, release-note-none

#1000 [CLD-6722] Upgrade Thanos to 0.33.0 and helm version 12.20.0
  internal/api/request_test.go
  model/cluster_utility.go
Labels: 4: Reviews Complete, release-note, kind/chore
