Repository mattermost/mattermost-cloud, pull requests merged in 2023-03, with the labels that each got.

#871 [MM-50968] E2E and logging improvements
  cmd/cloud/logger.go
  cmd/cloud/logger_hooks.go
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  e2e/pkg/webhook.go
  e2e/tests/cluster/cluster_test.go
  e2e/tests/cluster/suite.go
  e2e/tests/state/state.go
  e2e/workflow/cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#873 [MM-50538] Some logger and e2e field fixes
  cmd/cloud/logger_hooks.go
  e2e/workflow/cluster.go
Labels: 4: Reviews Complete, kind/bug, release-note

#876 rollback namespace deletion logic
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_provisioning.go
  k8s/namespaces.go
Labels: release-note-none

#868 Bump nginx and nginx-internal version
  internal/api/request_test.go
  model/cluster_utility.go
Labels: release-note, kind/chore

#877 [MM-51053] delete helm to cleanup LBs during cluster teardown
  internal/provisioner/cloudprober.go
  internal/provisioner/fluentbit.go
  internal/provisioner/helm_utils.go
  internal/provisioner/metrics_server.go
  internal/provisioner/nginx.go
  internal/provisioner/node_problem_detector.go
  internal/provisioner/pgbouncer.go
  internal/provisioner/prometheus_operator.go
  internal/provisioner/promtail.go
  internal/provisioner/rtcd.go
  internal/provisioner/teleport.go
  internal/provisioner/thanos.go
  internal/provisioner/utility_group.go
  internal/provisioner/velero.go
Labels: 2: Dev Review, release-note-none

#874 Remove redundant or unneeded AWS client access
  cmd/cloud/server.go
  internal/provisioner/eks_provisioner_cluster.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/kops_provisioner_cluster_installation.go
  internal/provisioner/kops_provisioner_test.go
  internal/provisioner/provisioner.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_installation.go
  internal/supervisor/cluster_installation_test.go
  internal/supervisor/cluster_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_db_restoration.go
  internal/supervisor/installation_test.go
  k8s/custom_resources_test.go
Labels: 2: Dev Review, kind/cleanup, release-note-none

#863 [MM-47885] Check subnet types are correct after a kops update
  cmd/cloud/workbench.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/cluster_management_test.go
Labels: kind/bug, release-note

#879 fix: awsClient reference
  internal/provisioner/kops_provisioner_cluster.go
Labels: kind/bug, release-note-none

#878 [MM-50968] Small fixes for e2e tests
  e2e/tests/cluster/cluster_test.go
  e2e/tests/cluster/suite.go
  e2e/workflow/cluster.go
Labels: 2: Dev Review, kind/bug, release-note

#869 [MM-50488] Enhance provisioning EKS cluster
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/installation.go
  cmd/cloud/workbench.go
  e2e/tests/cluster/suite.go
  e2e/workflow/cluster.go
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/mocks/aws-sdk/ec2.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/cluster.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/eks_provisioner_cluster.go
  internal/provisioner/k8s.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_cluster.go
  internal/provisioner/metrics_server.go
  internal/provisioner/nginx.go
  internal/provisioner/nginx_internal.go
  internal/provisioner/provisioner.go
  internal/store/cluster.go
  internal/store/cluster_dto_test.go
  internal/store/cluster_test.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/ec2.go
  internal/tools/aws/ec2_types.go
  internal/tools/aws/eks.go
  internal/tools/aws/eks_types.go
  model/cluster_eks.go
  model/cluster_eks_test.go
  model/cluster_request.go
  model/cluster_request_test.go
  model/eks_metadata.go
  model/kops_metadata.go
  model/provisioner_metadata.go
Labels: 2: Dev Review, release-note-none

#880 [MM-50968] More information on E2E test logs
  e2e/tests/cluster/cluster_test.go
Labels: kind/bug, release-note

#885 [MM-51440] Fixes server flag parsing in installation status command
  cmd/cloud/installation.go
  cmd/cloud/installation_flag.go
Labels: 2: Dev Review, release-note-none

#882 [MM-51265] Cluster resize support for EKS
  internal/api/cluster.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/eks_provisioner.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/eks.go
  internal/tools/aws/eks_types.go
Labels: 2: Dev Review, release-note-none

#890 Bump version for velero chart
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: 4: Reviews Complete, release-note, kind/chore

#887 chore: allow custom test flags
  Makefile
Labels: 4: Reviews Complete, release-note, kind/chore

#888 refactor: use generics for repeating code on DTO decoding
  model/client.go
  model/cluster_dto.go
  model/cluster_dto_test.go
  model/dtos.go
  model/group_dto.go
  model/group_dto_test.go
  model/installation_dto.go
  model/installation_dto_test.go
Labels: 2: Dev Review, kind/feature, release-note

#884 [MM-50968] fix: run mmctl command on running pods only
  internal/provisioner/exec.go
Labels: kind/bug, release-note

#893 Fix workflow not to run CD on PR
  .github/actions/docker-build/action.yaml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: kind/bug, release-note-none

#894 [MM-51583] Use 7.9.1 for mattermost-server
  e2e/pkg/installation_builder.go
Labels: 2: Dev Review, release-note-none

#886 [MM-50721] Provisioner: Update webhooks and subscriptions resources to store custom client header config
  cmd/cloud/events_subscription.go
  cmd/cloud/events_subscription_flag.go
  cmd/cloud/webhook.go
  cmd/cloud/webhook_flag.go
  internal/api/events_subscription_test.go
  internal/api/webhook.go
  internal/api/webhook_test.go
  internal/events/delivery.go
  internal/store/events_subscription.go
  internal/store/events_subscription_test.go
  internal/store/migrations.go
  internal/store/webhook.go
  internal/store/webhook_test.go
  internal/webhook/webhook.go
  model/events_state_change.go
  model/events_subscription.go
  model/events_subscription_request.go
  model/types.go
  model/types_test.go
  model/webhook.go
  model/webhook_request.go
  model/webhook_test.go
Labels: 2: Dev Review, kind/feature, release-note

#896 Add catalog-info.yaml for Backstage
  catalog-info.yaml
Labels: kind/feature, release-note-none

#891 [MM-51449] Manage multiple NodeGroups with EKS
  clusterdictionary/size.go
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  internal/api/cluster.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/eks_provisioner.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/ec2.go
  internal/tools/aws/eks.go
  model/cluster_request.go
  model/eks_metadata.go
  model/id.go
  model/kops_metadata.go
Labels: 2: Dev Review, release-note-none

#899 [MM-51746] Use dedicated LaunchTemplate for each NodeGroup [EKS]
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/eks_provisioner.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/ec2.go
  internal/tools/aws/eks.go
  model/aws_types.go
  model/cluster_request.go
  model/eks_metadata.go
Labels: 2: Dev Review, release-note-none
