Repository mattermost/mattermost-cloud, pull requests merged in 2024-09, with the labels that each got.

#1071 Add Mattermost debug data gathering
  cmd/cloud/cluster_installation.go
  cmd/cloud/cluster_installation_flag.go
  internal/api/cluster_installation.go
  internal/api/cluster_installation_test.go
  internal/api/common_test.go
  internal/api/context.go
  internal/api/helpers.go
  internal/provisioner/exec.go
  model/client.go
  model/cluster_installation.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#1072 Add second key to thanos-objstore-config in order to unify secrets but be BC at the same time keeping the old one
  internal/provisioner/utility/prometheus_operator.go
  internal/provisioner/utility/unmanaged.go
Labels: 2: Dev Review, 4: Reviews Complete, 2: Infra Review, release-note, kind/refactor

#1074 Fix typo in the certificate name
  internal/provisioner/utility/argo_utility.go
Labels: release-note-none

#1073 Remove deprecated server flags
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  go.mod
Labels: 2: Infra Review, kind/cleanup, release-note

#1075 [CLD-8390]Install aws-cli to docker image
  build/Dockerfile
Labels: kind/feature, release-note-none

#1076 [CLD-8390]Fix folder permissions
  build/Dockerfile
Labels: kind/bug, release-note-none

#1077 [CLD-8390]Fix cloud user home dir
  build/Dockerfile
Labels: release-note-none

#1079 Revert "[CLD-8390]Fix cloud user home dir"
  build/Dockerfile
Labels: release-note-none
