Repository mattermost/mattermost-cloud, pull requests merged in 2024-06, with the labels that each got.

#1054 Argocd improvements
  internal/provisioner/kops_provisioner.go
  internal/provisioner/utility/argo_utility.go
  internal/provisioner/utility/unmanaged.go
  internal/tools/argocd/application.go
Labels: 2: Dev Review, kind/feature, release-note-none

#1055 [CLD-7849]fix private certificate for nginx-internal
  internal/provisioner/utility/argo_utility.go
Labels: kind/bug, release-note-none

#1056 Use new bulk import flags
  internal/supervisor/import.go
Labels: 4: Reviews Complete, release-note

#1057 [CLD-7878]Remove unnecessary go routines + improve deletion process for utilities
  internal/provisioner/cluster_register.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/utility/argo_utility.go
  internal/provisioner/utility/unmanaged.go
  internal/tools/argocd/application.go
  internal/tools/argocd/client.go
  internal/tools/argocd/noop_client.go
Labels: kind/bug, release-note-none

#1058 Improve argocd provisioning resilience
  internal/provisioner/utility/argo_utility.go
  internal/tools/argocd/application.go
Labels: kind/feature, release-note-none
