Repository mattermost/mattermost-cloud, pull requests merged in 2024-05, with the labels that each got.

#1049 update nginx to 4.10.1
  internal/api/request_test.go
  model/cluster_utility.go
Labels: release-note

#1048 Use HOSTNAME env var for instanceID
  cmd/cloud/main.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1047 USe filepath to create custom dirs
  internal/provisioner/utility/argo_utility.go
Labels: kind/feature, release-note-none

#1050 Update Operator to version v1.22.0-rc.0
  helm-charts/mattermost-operator.yaml
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, release-note

#1051 Separate installation scheduling locks
  internal/api/cluster.go
  internal/api/context.go
  internal/api/lock.go
  internal/store/cluster.go
  internal/store/events.go
  internal/store/lock.go
  internal/store/migrations.go
  internal/supervisor/backup.go
  internal/supervisor/cluster.go
  internal/supervisor/cluster_lock.go
  internal/supervisor/cluster_test.go
  internal/supervisor/installation.go
  internal/supervisor/installation_deletion.go
  internal/supervisor/installation_test.go
  model/cluster.go
  model/cluster_states.go
  model/cluster_states_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1053 Attach permissions before argo provisioning operations
  internal/provisioner/cluster_provisioning.go
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#1052 Add option to prefer scheduling on stable clusters
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note
