Repository mattermost/mattermost-cloud, pull requests merged in 2024-01, with the labels that each got.

#997 Support ARM builds
  .github/actions/docker-build/action.yaml
  .github/actions/docker-prepare/action.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
  build/Dockerfile
  build/Dockerfile.e2e
  scripts/push-docker-e2e.sh
  scripts/push-image-pr.sh
  scripts/push-image.sh
Labels: 2: Dev Review, 2: Infra Review, release-note

#1001 update nginx to 4.9.0
  internal/api/request_test.go
  model/cluster_utility.go
Labels: release-note

#1002 Revert "Support ARM builds"
  .github/actions/docker-build/action.yaml
  .github/actions/docker-prepare/action.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
  build/Dockerfile
  build/Dockerfile.e2e
  scripts/push-docker.sh
  scripts/push-image-pr.sh
  scripts/push-image.sh
Labels: kind/bug

#986 Add custom errors page support
  model/ingress.go
  model/ingress_test.go
Labels: release-note

#1003 Cld 6836
  .github/actions/docker-build/action.yaml
  .github/actions/docker-prepare/action.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Makefile
  build/Dockerfile
  build/Dockerfile.e2e
  scripts/push-docker-e2e.sh
  scripts/push-image-pr.sh
  scripts/push-image.sh
Labels: kind/bug, kind/feature, release-note

#1005 [CLD-6943] Update MySQL default version to 8.0
  internal/tools/aws/constants.go
Labels: 4: Reviews Complete, release-note-none

#1004 Migrate Mattermost Operator deployment to Helm
  Makefile
  README.md
  cmd/cloud/server.go
  helm-charts/mattermost-operator.yaml
  internal/provisioner/cluster_provisioning.go
  internal/tools/helm/commands.go
  internal/tools/helm/run.go
  internal/tools/kops/run.go
  internal/tools/kubectl/cmd.go
  internal/tools/kubectl/commands.go
  internal/tools/kubectl/run.go
Labels: 4: Reviews Complete, release-note

#1006 Add Helm Charts directory to final docker image
  build/Dockerfile
Labels: 2: Dev Review, 2: Infra Review, kind/bug, release-note

#1010 [CLD-6960] Update default Teleport chart version to 8.3.21
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note, kind/chore

#1009 Helm client refactor and local chart install support
  .gitignore
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/provisioner.go
  internal/provisioner/utility/helm_utils.go
  internal/provisioner/utility/utility_group.go
  internal/tools/helm/cmd.go
  internal/tools/helm/commands.go
  internal/tools/helm/run.go
  internal/tools/kubectl/cmd.go
  internal/tools/kubectl/run.go
Labels: 4: Reviews Complete, release-note, kind/refactor

#1011 [CLD-7021] Release Teleport 9.3.26 as default version
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#1012 Ensure Mattermost Helm repo is added
  internal/provisioner/cluster_provisioning.go
Labels: 4: Reviews Complete, release-note

#1008 [CLD-6452] Replace duplication of pointer helpers like SToP with common util
  internal/api/cluster_test.go
  internal/api/common_test.go
  internal/api/db_multitenant_database_test.go
  internal/api/group_test.go
  internal/api/installation_test.go
  internal/store/installation_test.go
  internal/util/convert.go
  internal/util/convert_test.go
  model/cluster_installation_test.go
  model/cluster_request_test.go
  model/common_test.go
  model/group_request_test.go
  model/installation_dto_test.go
  model/installation_request_test.go
  model/installation_test.go
Labels: 2: Dev Review, release-note-none

#1013 Add Kubecfg env to raw output
  internal/tools/helm/commands.go
Labels: 4: Reviews Complete, release-note

#1007 Build image tags with timestamp
  Makefile
  build/Dockerfile
  scripts/push-image-pr.sh
Labels: 2: Dev Review, 2: Infra Review, release-note, kind/chore
