Repository mattermost/mattermost-cloud, pull requests merged in 2024-07, with the labels that each got.

#1059 Add external cluster importing
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/server.go
  internal/api/cluster.go
  internal/api/context.go
  internal/api/db_multitenant_database_test.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/external_provisioner.go
  internal/provisioner/installation_provisioner.go
  internal/provisioner/k8s.go
  internal/provisioner/provisioner.go
  internal/store/cluster.go
  internal/supervisor/import.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/cluster_external.go
  internal/tools/aws/database.go
  internal/tools/aws/database_multitenant.go
  internal/tools/aws/database_multitenant_pgbouncer.go
  internal/tools/aws/database_perseus.go
  internal/tools/aws/filestore.go
  internal/tools/aws/filestore_multitenant.go
  internal/tools/aws/s3.go
  internal/tools/aws/secrets_manager.go
  model/client.go
  model/cluster.go
  model/cluster_request.go
  model/cluster_request_test.go
  model/external_cluster_metadata.go
  model/provider.go
  model/provider_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1060 [CLD-7978]Add check to custom utility file to prevent override
  internal/provisioner/kops_provisioner.go
  internal/provisioner/utility/argo_utility.go
  internal/tools/argocd/application.go
  internal/tools/argocd/client.go
  internal/tools/argocd/noop_client.go
Labels: kind/feature, release-note-none

#1061 Use argocd to manage utilities for e2e-cluster
  e2e/tests/cluster/cluster_test.go
  e2e/tests/installation/installation_test.go
  e2e/tests/shared/shared.go
Labels: kind/feature, release-note-none

#1062 Log when webhook header values are empty
  internal/webhook/webhook.go
Labels: 2: Dev Review, release-note

#1063 Remove prometheus-operator from cluster e2e
  e2e/tests/shared/shared.go
Labels: release-note-none

#1064 Add VPC claiming for external cluster types
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  internal/api/cluster.go
  internal/api/context.go
  internal/api/db_multitenant_database_test.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/eks_provisioner.go
  internal/provisioner/external_provisioner.go
  internal/store/cluster.go
  internal/supervisor/installation.go
  internal/tools/aws/cluster_management.go
  internal/tools/aws/cluster_management_test.go
  internal/tools/aws/vpc.go
  model/cluster.go
  model/cluster_request.go
  model/cluster_test.go
  model/external_cluster_metadata.go
  model/external_provider_metadata.go
  model/installation.go
  model/installation_database.go
  model/installation_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1065 bump nginx and nginx-internal
  internal/api/request_test.go
  model/cluster_utility.go
Labels: release-note

#1066 Update Go modules and Mattermost Operator to v1.22.0
  build/Dockerfile
  build/Dockerfile.e2e
  go.mod
  go.sum
  helm-charts/mattermost-operator.yaml
  internal/tools/cloudflare/dns.go
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, release-note, kind/chore

#1067 Add VPC cluster type tag check
  internal/tools/aws/cluster_management.go
  internal/tools/aws/constants.go
Labels: 4: Reviews Complete, release-note
