Repository mattermost/mattermost-cloud, pull requests merged in 2024-12, with the labels that each got.

#1086 Add support for --context flag
  cmd/cloud/clicontext/clicontext.go
  cmd/cloud/main.go
Labels: release-note-none

#1087 Add support for contexts requiring confirmation
  cmd/cloud/clicontext/clicontext.go
  cmd/cloud/contexts.go
  cmd/cloud/login.go
  cmd/cloud/main.go
Labels: 4: Reviews Complete, release-note-none

#1089 Add option to always schedule on external clusters
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  model/cluster.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1088 QOL: Add ClusterIDs array to InstallationDTO object
  internal/api/installation.go
  internal/store/cluster_installation.go
  internal/store/installation_dto.go
  internal/store/installation_dto_test.go
  model/installation.go
  model/installation_dto.go
Labels: 4: Reviews Complete, release-note-none

#1091 [CLD-8628 #2] Add custom status code for installation name/dns conflicts + bonus
  Makefile
  internal/api/installation.go
  internal/api/installation_test.go
  internal/store/installation.go
  internal/store/installation_dns.go
  internal/store/util.go
Labels: 4: Reviews Complete, release-note-none

#1092 Add custom installation volume support
  cmd/cloud/installation.go
  cmd/cloud/installation_flag.go
  internal/api/context.go
  internal/api/db_multitenant_database_test.go
  internal/api/installation.go
  internal/api/installation_test.go
  internal/mocks/aws-sdk/secrets_manager.go
  internal/mocks/aws-tools/client.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/store/installation.go
  internal/store/migrations.go
  internal/supervisor/installation.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/secrets_manager.go
  internal/tools/aws/secrets_mangager_types.go
  internal/tools/utils/utils.go
  model/client.go
  model/installation.go
  model/installation_request.go
  model/pgbouncer.go
  model/volumes.go
  model/volumes_test.go
Labels: 4: Reviews Complete, kind/feature, release-note
