Repository mattermost/mattermost-cloud, pull requests merged in 2024-04, with the labels that each got.

#1032 Change AMI handling for kops metadata
  internal/tools/kops/instance_groups.go
  model/kops_metadata.go
Labels: 4: Reviews Complete, release-note

#1017 [CLD-5863] Enabling provisioner to deploy utilities using Argocd.
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  go.mod
  go.sum
  internal/api/request_test.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/cluster_register.go
  internal/provisioner/eks_provisioner.go
  internal/provisioner/kops_provisioner.go
  internal/provisioner/kops_provisioner_test.go
  internal/provisioner/utility/argo_utility.go
  internal/provisioner/utility/cloudprober.go
  internal/provisioner/utility/fluentbit.go
  internal/provisioner/utility/metrics_server.go
  internal/provisioner/utility/nginx.go
  internal/provisioner/utility/nginx_internal.go
  internal/provisioner/utility/node_problem_detector.go
  internal/provisioner/utility/pgbouncer.go
  internal/provisioner/utility/prometheus_operator.go
  internal/provisioner/utility/promtail.go
  internal/provisioner/utility/rtcd.go
  internal/provisioner/utility/teleport.go
  internal/provisioner/utility/thanos.go
  internal/provisioner/utility/unmanaged.go
  internal/provisioner/utility/utility_group.go
  internal/provisioner/utility/velero.go
  internal/tools/argocd/application.go
  internal/tools/argocd/argocd_apps.go
  internal/tools/argocd/argocd_apps_test.go
  internal/tools/argocd/client.go
  internal/tools/git/client.go
  internal/tools/git/git.go
  internal/tools/git/noop_client.go
  model/cluster_utility.go
Labels: kind/feature, release-note

#1031 Update Mattermost Operator to v1.21.0
  build/Dockerfile
  build/Dockerfile.e2e
  go.mod
  go.sum
  manifests/operator-manifests/mattermost/operator.yaml
Labels: 4: Reviews Complete, release-note, kind/chore

#1034 upgrade argocdv2
  go.mod
  go.sum
Labels: 2: Dev Review, release-note-none

#1035 Add per-cluster PgBouncerConfig
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/api/request_test.go
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/pgbouncer/pgbouncer.go
  internal/provisioner/pgbouncer/pgbouncer_test.go
  internal/provisioner/provisioner.go
  internal/store/cluster.go
  internal/store/cluster_dto_test.go
  internal/store/cluster_test.go
  internal/store/migrations.go
  model/cluster.go
  model/cluster_request.go
  model/pgbouncer.go
  model/pgbouncer_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1033 Support arm AMI IG rollouts. Support AMI names and not only AMI IDs
  cmd/cloud/cluster.go
  internal/provisioner/kops_utils.go
  internal/provisioner/kops_utils_test.go
  internal/tools/aws/acm_test.go
  internal/tools/aws/client_test.go
  internal/tools/aws/ec2.go
  internal/tools/aws/ec2_test.go
Labels: release-note

#1036 Flag cleanup
  cmd/cloud/cluster_flag.go
  cmd/cloud/installation_flag.go
  cmd/cloud/server_flag.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#1037 Feat/cld 7531
  internal/provisioner/kops_provisioner.go
  internal/provisioner/utility/utility_group.go
  internal/tools/argocd/client.go
  internal/tools/argocd/noop_client.go
  model/cluster_utility.go
Labels: kind/feature, release-note-none

#1039 [CLD-6745]Update metrics-server
  internal/api/request_test.go
  internal/provisioner/utility/metrics_server_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: kind/feature, release-note-none

#1038 Fix AMI flag help notes
  cmd/cloud/cluster_flag.go
Labels: release-note

#1041 Feat/cld 7451
  internal/provisioner/utility/argo_utility.go
  internal/provisioner/utility/utility_group.go
Labels: kind/feature, release-note-none

#1042 Adding context to err in substitutevalues function
  internal/provisioner/utility/argo_utility.go
Labels: release-note-none

#1043 Create cluster dir for argocd output custom values
  internal/provisioner/utility/argo_utility.go
Labels: kind/bug, release-note-none
