Repository mattermost/mattermost-cloud, pull requests merged in 2024-03, with the labels that each got.

#1024 Feat/add binary tarballs on release
  .github/workflows/cd.yml
  .gitignore
  Makefile
  build/Dockerfile
Labels: kind/feature, release-note-none

#1026 fix: Upgrade actions and use clean Makefile commands to push tags
  .github/actions/docker-build/action.yaml
  .github/actions/docker-prepare/action.yml
  .github/workflows/ci.yml
  Makefile
  scripts/push-image.sh
Labels: kind/bug, release-note-none

#1025 Add logic to skip AMI updates for instance groups
  internal/provisioner/kops_utils.go
  internal/tools/kops/instance_groups.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#1028 Support AMI suffix overrides
  internal/provisioner/kops_utils.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1027 Bump NPD to support ARM architecture
  internal/api/request_test.go
  internal/provisioner/utility/node_problem_detector_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#1029 feat: Introduce --header global variable to access provisioner with auth
  cmd/cloud/backup.go
  cmd/cloud/cluster.go
  cmd/cloud/cluster_annotation.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/cluster_installation.go
  cmd/cloud/dashboard.go
  cmd/cloud/dashboard_flag.go
  cmd/cloud/databases.go
  cmd/cloud/events.go
  cmd/cloud/events_flag.go
  cmd/cloud/events_subscription.go
  cmd/cloud/group.go
  cmd/cloud/group_annotation.go
  cmd/cloud/installation.go
  cmd/cloud/installation_annotation.go
  cmd/cloud/installation_dns.go
  cmd/cloud/installation_operation_db_migration.go
  cmd/cloud/installation_operation_restoration.go
  cmd/cloud/nodegroup.go
  cmd/cloud/security.go
  cmd/cloud/security_flag.go
  cmd/cloud/utils.go
  cmd/cloud/webhook.go
  cmd/cloud/webhook_flag.go
  cmd/cloud/workbench.go
  cmd/cloud/workbench_flag.go
Labels: kind/feature, release-note

#1030 Fix serverAddress flag duplication
  cmd/cloud/dashboard_flag.go
  cmd/cloud/security_flag.go
  cmd/cloud/webhook_flag.go
  cmd/cloud/workbench_flag.go
Labels: 4: Reviews Complete, kind/regression, release-note
