Repository mattermost/mattermost-cloud, pull requests merged in 2024-10, with the labels that each got.

#1078 [CLD-8399]Remove promtail from utility list when use argocd
  e2e/tests/shared/shared.go
  internal/provisioner/utility/unmanaged.go
Labels: kind/feature, release-note-none

#1080 fix aws-cli path permission
  build/Dockerfile
  build/bin/user_setup
Labels: release-note-none

#1081 Bump write timeout in bifrost
  manifests/bifrost/bifrost.yaml
Labels: release-note

#1083 'Upgrade' version of k8s.io/client-go to proper format
  go.mod
Labels: release-note-none

#1084 Fix structs to match argocd YAML files
  internal/provisioner/utility/unmanaged.go
  internal/tools/argocd/argocd.go
  internal/tools/argocd/argocd_apps.go
Labels: kind/bug, release-note-none
