Repository mattermost/mattermost-cloud, pull requests merged in 2024-02, with the labels that each got.

#1015 Use targetplatform, targetarch. Add multiarch to e2e.
  build/Dockerfile
  build/Dockerfile.e2e
Labels: release-note

#1016 Try to fix respecting pull requests tags
  .github/actions/docker-build/action.yaml
Labels: kind/bug, release-note

#979 Support argocd cluster register/deregister
  cmd/cloud/cluster.go
  cmd/cloud/cluster_flag.go
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  go.mod
  go.sum
  internal/api/cluster.go
  internal/api/cluster_test.go
  internal/provisioner/cluster_provisioning.go
  internal/provisioner/cluster_register.go
  internal/provisioner/kops_provisioner.go
  internal/tools/argocd/argocd.go
  internal/tools/argocd/argocd_test.go
  internal/tools/git/client.go
  internal/tools/git/git.go
  internal/tools/git/noop_client.go
  k8s/kubeconfig.go
  model/cluster_request.go
  model/cluster_request_test.go
  model/cluster_utility.go
Labels: kind/feature, release-note

#1018 Update kops version to 1.27.10
  Makefile
Labels: release-note, kind/chore

#1019 Change to Kops 1.27.3
  Makefile
Labels: kind/bug, release-note

#1020 add multiple platforms to e2e builds
  .github/actions/docker-build/action.yaml
  Makefile
  scripts/push-docker-e2e.sh
Labels: release-note

#1021 [CLD-7223] Upgrade Thanos to 0.34.1
  internal/api/request_test.go
  model/cluster_utility.go
Labels: release-note, kind/chore

#1023 [CLD-7224] Upgrade Promtail to 2.9.3 in all envs
  internal/api/request_test.go
  model/cluster_utility.go
  model/cluster_utility_test.go
Labels: release-note

#1022 Add logging to S3LargeCopy
  internal/mocks/aws-tools/client.go
  internal/supervisor/import.go
  internal/supervisor/import_test.go
  internal/supervisor/installation_test.go
  internal/tools/aws/client.go
  internal/tools/aws/s3.go
Labels: 4: Reviews Complete, kind/feature, release-note
