Repository mattermost/mattermost-cloud, pull requests merged in 2025-06, with the labels that each got.

#1112 Add server flags for pod probe overrides
  cmd/cloud/server.go
  cmd/cloud/server_flag.go
  cmd/cloud/server_flag_test.go
  go.mod
  go.sum
  internal/provisioner/cluster_installation_provisioner.go
  internal/provisioner/cluster_installation_provisioner_test.go
  internal/provisioner/provisioner.go
Labels: 4: Reviews Complete, kind/feature, release-note

#1113 Log API calls when group ID is invalid
  internal/api/lock.go
Labels: 4: Reviews Complete, release-note

#1114 Add Claude
  .github/workflows/claude.yml
Labels: release-note-none

#1116 pin down checkout version for workflow
  .github/workflows/claude.yml
Labels: release-note-none
