Repository mattermost/mattermost-cloud, pull requests merged in 2025-04, with the labels that each got.

#1104 bump installation version
  e2e/pkg/installation_builder.go
Labels: release-note-none

#1103 update pgbouncer config when execute cluster provision for external clusters
  internal/provisioner/eks_provisioner.go
  internal/provisioner/external_provisioner.go
Labels: release-note

#1106 skip utility deployment if it's already managed by argocd
  internal/provisioner/utility/unmanaged.go
Labels: release-note-none

#1107 Update E2E tests to shorten deletion expiry
  e2e/pkg/installation.go
  e2e/workflow/installation.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#1108 Bump workflow images to ubuntu-24.04
  .github/workflows/ci.yml
Labels: release-note-none
